### ISSUE TITLE
Wrong results while using '__in' field lookup

### ISSUE THREAD

**Issue by nabucosound** [stefanfoulis/django-phonenumber-field#10]
Given a Profile model with a PhoneNumberField called 'phone_number', if we have invalid phone numbers stores, such as:

    obj = Profile()
    obj.phone_number = 'foo'
    obj.save()

Then we run a queryset using '__in':

    Profile.objects.filter(phone_number__in=['bar'])

We get the object in the results.

It is a weird behavior, as the internal database field (I am using MySQL) is saved as a varchar. What is happening here?

**Comment by amateja** [comment]
Thank you for reporting. Our project has evolved since that time and this issue will be closed. Please update and reopen if you feel it is still applicable.
