### ISSUE TITLE
Can't set field to blank value once it has been populated

### ISSUE THREAD

**Issue by bfriedmann71** [stefanfoulis/django-phonenumber-field#106]
I am not sure if this is a bug or not, but I am having trouble getting the model to update the field to a blank value.  The scenario is that when the record was created initially, a phone number was provided and correctly populated this field, but if I then go back and try to update that record and set the phone number field to blank ('') it will not take and does not get applied in the underlying model/database.  The code works when you start with a blank value and then populate it, but what about starting with a populated field and try to remove the value?  If someone provided a fax number, how do I update my record to a blank value if the end user no longer has a fax number?  My scenario assumes the field has been defined only with blank=True and default='' similar to the fax_number field in your Basic Usage example.

**Comment by techdragon** [comment]
its a bug from what I can see... probably the same as #1 and #102

**Comment by amateja** [comment]
It is fixed and tested.
