### ISSUE TITLE
phonenumberslite fallback not working as intended

### ISSUE THREAD

**Issue by scop** [stefanfoulis/django-phonenumber-field#120]
```
$ pip list | grep phonenumber
django-phonenumber-field (1.0.0)
phonenumbers (7.2.8)

$ grep phonenumber requirements.txt 
django-phonenumber-field~=1.1.0

$ pip install -Ur requirements.txt
[...]
Installing collected packages: phonenumberslite, django-phonenumber-field
  Running setup.py install for phonenumberslite ... done
  Found existing installation: django-phonenumber-field 1.0.0
    Uninstalling django-phonenumber-field-1.0.0:
      Successfully uninstalled django-phonenumber-field-1.0.0
Successfully installed django-phonenumber-field-1.1.0 phonenumberslite-7.2.8
```

So the full phonenumbers was already installed, but pip ended up installing phonenumberslite anyway. And now it's a bit of a mess, need to fix things manually (remove both phonenumberslite and phonenumbers and reinstall one of them).

**Comment by amateja** [comment]
It turns out that it was not the best idea to replace phonenumbers dependency to phonenumberslite gracefully. Currently I have no suggestion how to do it better. I'm afraid if we don't find solutions really fast it will never be fixed.

**Comment by scop** [comment]
My hunch is that a better solution than the current one should be provided by phonenumbers upstream. Downstream projects should not need to play games like this in order to be flexible between the two. I suggest simply reverting back to full phonenumbers for the time being in django-phonenumber-field.

**Comment by scop** [comment]
Ping?

**Comment by amateja** [comment]
pong :smile:

Hi @scop,

I totally agree with you - phonenumbers project should rethink their packaging. I've submitted them no issue because I'm not packaging expert. Probably the simplest way is to keep phonenumberslite and gut phonenumbers of everything what is already in lite and add lite as its dependency. I'm not very sure if we should take recent changes back... but even though I cannot do that - only @stefanfoulis is able to issue a new version.

**Comment by vstoykov** [comment]
Probably will be better to remove `phonenumbers`/`phonenumberslite` from `install_requires` and add them in `extras_require`. Then the installation to be:

    pip install django-phonenumber-field[full]

or 

    pip install django-phonenumber-field[lite]

By this way anybody can set this to it's `requirements.txt` file or just use `django-phonenumber-field` without any extra and specify which package of phonenumbers they require.

I know that `phonenumbers` is a requirement for this package to work but there will be cases that one group of users will want the lite version and the others may want full version for other reasons.

What do you think about that?

P.S. Django is also a requirement but is not listed in install requires :wink:

**Comment by Duologic** [comment]
Too bad this hasn't been picked up yet. I'm running into the same problem here.

**Comment by Duologic** [comment]
For the workaround: 

I've installed `phonenumberslite` instead. According to the Readme of the project, you probably won't need the full version anyway. 

https://github.com/daviddrysdale/python-phonenumbers#memory-usage

**Comment by stefanfoulis** [comment]
in 2.1.0 we removed the hardcoded dependecy to `phonenumbers`. Now can choose yourself which one to manually install.
