### ISSUE TITLE
Recommendation for usage within `django-localflavor`

### ISSUE THREAD

**Issue by orf** [stefanfoulis/django-phonenumber-field#121]
Hey there,
The `django-localflavor` (https://github.com/django/django-localflavor) package is considering dropping all their phone number validations in favour of this package, because it's much more complete. Possibly in the next release we will add deprecation warnings, and then fully remove them in about a year.

I guess this is just a heads up, but I also just wanted to make sure that this was acceptable? It might increase the development burden on you and if this is a problem then please say. If it is not a problem then we could start to discuss ways to make the transition as easy as possible for existing users of the localflavor library?

**Comment by kevin-brown** [comment]
I took a really quick look through the [django-localflavor tickets](https://github.com/django/django-localflavor) and couldn't find anything on their side where this was being discussed.

The closest thing I found was https://github.com/django/django-localflavor/pull/208, though that doesn't have much of a discussion on it.

**Comment by orf** [comment]
The talk has been offline for now, but the jist is this package (and the underlying libphonenumber) is far superior to localflavours, so is there much point in improving our existing implementation when we can suggest yours?

**Comment by benkonrath** [comment]
There's also a stalled PR about making a generic phone number field but it doesn't make sense considering this package.
https://github.com/django/django-localflavor/pull/142

localflavor PR 208 is about working out the details of the deprecation policy. There will be a separate proposal or PR about actually deprecating the phone number fields. We'd love to here your thoughts on the phone number field deprecation when we have a proposal or PR filed. One of us will post a link here when it's ready.

**Comment by benkonrath** [comment]
The phone number fields in django-localflavor have been deprecated as of version 1.4 and we're now recommending this project. I think this issue can be closed. Thanks.

**Comment by stefanfoulis** [comment]
awesome, thanks @benkonrath
