### ISSUE TITLE
Running migration on phonenumberfield results in AttributeError

### ISSUE THREAD

**Issue by dedayoa** [stefanfoulis/django-phonenumber-field#123]
I've got the straight up install of django-phonenumber-field, with phonenumberslite.
See extract from running pipdeptree below.

`django-phonenumber-field==1.1.0
  - phonenumberslite [required: >=7.0.2, installed: 7.3.1]
  - babel [installed: 2.3.3]
    - pytz [required: >=0a, installed: 2016.3]`

When I run manage.py migrate, I get 

`  File "C:\Users\...\lib\site-packages\phonenumber_field\modelfields.py", line 76, in get_prep_value
    return value.format_as(fmt)
AttributeError: 'NoneType' object has no attribute 'format_as'`

as the last entry in the error trace.

I'm running Python 3.4.3
Any suggestion to what is causing this? How can I remedy as it is preventing my migrations from successfully running.

**Comment by banagale** [comment]
Thank you for the report and fix on this.
