### ISSUE TITLE
 NameError: name 'PhoneNumberField' is not defined

### ISSUE THREAD

**Issue by daneshg** [stefanfoulis/django-phonenumber-field#129]
In model.Model
phone_no = PhoneNumberField()
NameError: name 'PhoneNumberField' is not defined

**Comment by amateja** [comment]
Hi @daneshg

Have you imported `phonenumber` package? With so little details there is not much we can help you with.

**Comment by daneshg** [comment]
i am sorry 
i forgot to save after importing

**Comment by amateja** [comment]
It's all right :smile:. Glad I could help. Can I close this issue?

**Comment by daneshg** [comment]
ya

**Comment by daneshg** [comment]
thanks for the quick help........

**Comment by amateja** [comment]
Cheers!
