### ISSUE TITLE
django>=1.5 should be added to install_requires 

### ISSUE THREAD

**Issue by tisdall** [stefanfoulis/django-phonenumber-field#130]
There doesn't seem to be any listing for `django` in the `setup.py` file.  I'm not sure which versions this library works with, but the Travis files seem to indicate that it's only being tested with Django 1.5 and greater.  So, `setup.py` should probably match what's being covered by testing.

**Comment by amateja** [comment]
Hi @tisdall 

You seems to be right. Although I would drop support for unsupported Django versions. It's a bit wired to keep extra code for a version which is not maintained November 2013, isn't it? Currently I have not enough time to start such huge redesign but if you are keen to give us a hand we would welcome any help.

**Comment by tisdall** [comment]
Well, I wasn't advocating a huge rewrite, just adding documentation of what's currently supported/required to the `setup.py`.
