### ISSUE TITLE
Not working with Model Mixin

### ISSUE THREAD

**Issue by vaibhav-jain** [stefanfoulis/django-phonenumber-field#134]
If I use `Django phonenumber-field` directly then `Django` detects it and applies the `migrations` properly but If I use `Django phonenumber-field` with mixin (abstract model) then `Django` fails to detect the changes. Can you tell me how to fix this ???

**Comment by stefanfoulis** [comment]
I'm doing some cleanup of old issues. Please re-open if this is still an issue.
