### ISSUE TITLE
PhoneNumberPrefixWidget, problem with 'required'

### ISSUE THREAD

**Issue by dilrajsachdev** [stefanfoulis/django-phonenumber-field#138]
Hi,

Thanks for django-phonenumber-field

When I am using django-phonenumber-field widget with `required=True` , it works fine but if I change to  `required=False`  then also it is not allow to submit empty.

What I found is in  `class PhoneNumberPrefixWidget`  and in method 'value_from_datadict', even when there is no data it will return dot(.) and that will be raise an validation error

If I change like this, then it works

```
def value_from_datadict(self, data, files, name):
        values = super(PhoneNumberPrefixWidget, self).value_from_datadict(
            data, files, name)
        if all(values):
            return '%s.%s' % tuple(values)
        return ''
```

But if you try above code with `required=True` then it will throw error because there is no required message is set but this can be set on form level for now, by setting error_messages 

Thanks

**Comment by archatas** [comment]
I also experienced the same problem and solved it temporarily by extending the `PhoneNumberPrefixWidget` and overwriting the `value_from_datadict` method in my code like this:

```
from phonenumber_field.widgets import PhoneNumberPrefixWidget as PhoneNumberPrefixWidgetBase

class PhoneNumberPrefixWidget(PhoneNumberPrefixWidgetBase):
    def value_from_datadict(self, data, files, name):
        values = super(PhoneNumberPrefixWidgetBase, self).value_from_datadict(
            data, files, name)
        if all(values):
            return '%s.%s' % tuple(values)
        return ""

```

**Comment by dilrajsachdev** [comment]
Thanks, yeah I did this for now, maybe I will change it later

**Comment by dmarcelino** [comment]
Stumbled upon this issue as well. The proposed solution works fine, thanks!

**Comment by haidaraM** [comment]
Same issue for me. This should be fixed.

**Comment by aliceni81** [comment]
Hi, this issue happens again in v6.3.0

**Comment by francoisfreitag** [comment]
Should be resolved with https://github.com/stefanfoulis/django-phonenumber-field/pull/512.
