### ISSUE TITLE
Is there any way to enter toll free numbers like 1800 ... ?

### ISSUE THREAD

**Issue by abhinavnair** [stefanfoulis/django-phonenumber-field#146]
I would like to store numbers like 1800, etc. Is there any way to do this. Currently this number shows as invalid.

**Comment by jdufresne** [comment]
This works for me. 

If this is still an issue, can you provide additional details as to what is failing with a reproducible test case?

```
>>> from phonenumber_field.phonenumber import PhoneNumber
>>> pn = PhoneNumber.from_string('1-800-345-1234', region='US')
>>> pn.is_valid()
True
```
