### ISSUE TITLE
Filtering for phone number issue

### ISSUE THREAD

**Issue by JulianSchneider** [stefanfoulis/django-phonenumber-field#149]
I'm using a filter like this:

`connection = NumberConnection.objects.filter(host__phone__contains=origin_number)`

where phone is a phonenumber field. 

The number is a international number and there is one matching that in the database.

Funny thing is: on my windows dev machine this query returns the correct object. On my linux server it doesnt. 

I validated by taking the objects and check if the numbers are equal. (Calling host.phone.as_international on both machines.) The version of the python plugin is the same machines, the database system is postgresql for both.

Edit: I figured out that the linux machine had spaces in the number, upon resaving they vanished. Can't reproduce this o.O

**Comment by jdufresne** [comment]
> Edit: I figured out that the linux machine had spaces in the number, upon resaving they vanished. Can't reproduce this o.O

Makes sense. Thanks for updating!
