### ISSUE TITLE
Proper documentation

### ISSUE THREAD

**Issue by munikarmanish** [stefanfoulis/django-phonenumber-field#152]
Are you guys thinking about writing a proper (detailed) documentation in readthedocs?

**Comment by pythonpro** [comment]
And pls don't forget to drop section about adding django-phonenumber-field to INSTALLED_APPS. There's no need for this since the app doesn't have its own models.

**Comment by jdufresne** [comment]
> And pls don't forget to drop section about adding django-phonenumber-field to INSTALLED_APPS. There's no need for this since the app doesn't have its own models.

The `INSTALLED_APPS` entry is required for translations. See the Django docs:

https://docs.djangoproject.com/en/2.2/topics/i18n/translation/#how-django-discovers-translations

> Then, it looks for and uses if it exists a locale directory in each of the installed apps listed in INSTALLED_APPS. The ones appearing first have higher precedence than the ones appearing later.
