### ISSUE TITLE
PhoneNumberInternationalFallbackWidget is not working as expected

### ISSUE THREAD

**Issue by pymarco** [stefanfoulis/django-phonenumber-field#154]
**Results**
Enter "+447700900466"
Saved as country_code "1" and national_number "7700900466"

I expect that it would save with country_code "44".

**Settings**
```
PHONENUMBER_DB_FORMAT = "NATIONAL"
PHONENUMBER_DEFAULT_REGION = "US"
```

**Model**
```
class PhoneNumber(models.Model):
    label = models.CharField(
        verbose_name="Label",
        max_length=128,
        default='',
        blank=True)

    number = PhoneNumberField(
        verbose_name="Phone",
        max_length=30,
        default='',
        blank=True)

    extension = models.CharField(
        verbose_name="Extension",
        max_length=30,
        default='',
        blank=True)
```

**Form**
```
class PhoneNumber(forms.ModelForm):
    class Meta:
        model = models.PhoneNumber

        fields = [
            'label',
            'number',
            'extension',
        ]

        widgets = {
            'number': PhoneNumberInternationalFallbackWidget(),
        }
```

**Comment by pymarco** [comment]
I stepped through the code and it seems that `_format_value` is never called during save.

**Comment by amateja** [comment]
I could write a quite long response but I think your problem might be answered with issue #153. You are storing only part of your phone number in database - a national one and you are loosing international part. When you retrieve it from database it take default region, which is in your case as you described `'US`. This is why you get what you get.

Definitely it must be change and it shouldn't be allowed to loose any data.

**Comment by pymarco** [comment]
Thank you for responding. From the link you provided I learned that I needed to removed `PHONENUMBER_DB_FORMAT` from my custom settings.
