### ISSUE TITLE
How to update my local data

### ISSUE THREAD

**Issue by vishnuku** [stefanfoulis/django-phonenumber-field#158]
Hey Folk,

Can you guide me how to update my local data of newly supported phone number added to this

**Comment by amateja** [comment]
Hello @vishnuku. Could you elaborate a bit more on what's your problem?

**Comment by stefanfoulis** [comment]
@vishnuku I suppose you mean the various phone number formats used for validation. These are part of the phonenumbers package on pypi and the latest version can be retrieved by installing the latest version of that package.

Please re-open this issue if I misunderstood the question.
