### ISSUE TITLE
How to filter records with empty value for PhoneNumberField?

### ISSUE THREAD

**Issue by lukaszolek** [stefanfoulis/django-phonenumber-field#159]
Model.objects.filter(phone="") does not work.
Model.objects.filter(phone__isnull = True) neither.

How to do this?

**Comment by lampslave** [comment]
`Model.objects.filter(phone="")` compiles into sql as `SELECT * FROM table_name WHERE phone=None AND phone IS NOT NULL`. #161 should fix it.
