### ISSUE TITLE
French number with format +33712345678

### ISSUE THREAD

**Issue by NameX44** [stefanfoulis/django-phonenumber-field#160]
Hi,

PhoneNumberField doesn't validate for french number with the following format :  

+33712345678

Could you fix it please ?
Thanks

**Comment by amateja** [comment]
Unfortunately we can't. Please refer to #166.

**Comment by ahumeau** [comment]
This is not a valid French phone number, when French numbers start with 07, the third digit must be between 3 and 9 [source](https://www.arcep.fr/index.php?id=8146). [Equivalent libphonenumber issue](https://github.com/googlei18n/libphonenumber/issues/500).

**Comment by stephane** [comment]
This issue should be closed.
