### ISSUE TITLE
Update PyPI package to be on par with Github

### ISSUE THREAD

**Issue by kootoopas** [stefanfoulis/django-phonenumber-field#165]
Hello.

The package uploaded on PyPI hasn't been updated since March 2016, thus, to get the latest bug fixes & features one has to `pip install git+https://github.com/stefanfoulis/django-phonenumber-field/`, straight from the repo.

I mean it's fine this way, but I recon that some people won't be able to figure out why code isn't behaving as it should. 🙂

**Comment by stefanfoulis** [comment]
1.2.0 Released. Thanks for reminding me.
