### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by spenoir** [stefanfoulis/django-phonenumber-field#17]
It is not currently possible to install via pip or git at the moment for me:

$ pip install django-phonenumber-field
Downloading/unpacking django-phonenumber-field
  Could not find a version that satisfies the requirement django-phonenumber-field (from versions: 0.2a1, 0.2a3)
Cleaning up...
No distributions matching the version for django-phonenumber-field
Storing complete log in /Users/add/.pip/pip.log

**Comment by stefanfoulis** [comment]
this was likely newer versions of pip ignoring non final versions by default. we have final releases now, so this should no longer be an issue.
