### ISSUE TITLE
TypeError when PhoneNumber used inline in Admin

### ISSUE THREAD

**Issue by wojtek-fliposports** [stefanfoulis/django-phonenumber-field#170]
Regarding to ticket: https://code.djangoproject.com/ticket/26819

>This is not related to the database and is purely a Python issue. This is not limited to ArrayField; any custom field may be affected. In our case, the phonenumber_field.modelfields.PhoneNumberField is causing the error unhashable type: 'PhoneNumber'. Since Django documentation does not mandate that custom fields are hashable (i.e., define the __hash__() method), I suppose that most of the existing non-builtin fields are affected.

It's also possible dupplication of #93

**Comment by tredzko** [comment]
Per your environment in #93, and to duplicate my question for those who might search for this:
Have you tried upgrading your django-phonenumber-field? The current version is [1.3.0](https://pypi.python.org/pypi/django-phonenumber-field/1.3.0), yours appears to be pinned to 1.0.0. 1.3.0 has the changes from #151 added to it.

**Comment by wojtek-fliposports** [comment]
version 1.3.0 solves problem.. I have been using 1.1.0
