### ISSUE TITLE
German localization files

### ISSUE THREAD

**Issue by deluge** [stefanfoulis/django-phonenumber-field#171]
The *.po file for de is marked as fuzzy. So If I use de locale I get english error messages etc.

**Comment by amateja** [comment]
Thanks for your report. I know where problem might be. Could you double check our de localization file to verify if translation is made properly? https://github.com/stefanfoulis/django-phonenumber-field/blob/master/phonenumber_field/locale/de/LC_MESSAGES/django.po

**Comment by Mactory** [comment]
I just checked the translation file you posted. The German translation is correct. You can remove the fuzzy mark.
