### ISSUE TITLE
Support multiple formats

### ISSUE THREAD

**Issue by adambyer** [stefanfoulis/django-phonenumber-field#173]
Is it possible to support more than one format?... for example allow with or without +

**Comment by amateja** [comment]
Actually it's not and it's not due to django-phonenumber-field. This package relies on https://github.com/daviddrysdale/python-phonenumbers and all conversion magic is made by it. Please also have a look on #166. It's not strictly related to your problem but it might give you some hit.

**Comment by adambyer** [comment]
Thanks for the response. I see in python-phonenumbers that the parse method takes a 2nd argument for the region. Wouldn't it be possible to have the PHONENUMBER_DB_FORMAT (or other) setting contain a list of supported formats, and then have parse cycle through them to see if any match? Or something like that?

**Comment by BillBrower** [comment]
@adambyer Yes it should be. 
@stefanfoulis  If someone was to submit a PR that did what Adam is suggesting would you accept it?

**Comment by chrisspen** [comment]
Why was this closed? I ran into this issue as well. Are multiple formats supported? The underlying phonenumbers package is unrelated to this package iterating over a list of formats.

**Comment by francoisfreitag** [comment]
The `parse` method supports multiple formats: https://github.com/daviddrysdale/python-phonenumbers#example-usage
For national phone numbers, which can be ambiguous, a region should be specified.

As for what’s in your DB, you should use a single format. That will simplify exports and integration with other systems, give you a deterministic representation of the data. Using multiple formats for the database is not recommended. Unless one can present a compelling use case for this “feature”, I don’t think it should be provided.
