### ISSUE TITLE
AttrributeError: The 'phone' attribute can only be accessed from X instances.

### ISSUE THREAD

**Issue by flc** [stefanfoulis/django-phonenumber-field#175]
since this change https://github.com/django/django/commit/37ab3c3f9d707d6a1896db79c631e920dcb1fb78 in django 1.11.2 get_or_create calls raise exceptions like `AttributeError: The 'phone' attribute can only be accessed from Account instances.` here https://github.com/stefanfoulis/django-phonenumber-field/blob/master/phonenumber_field/modelfields.py#L32

**Comment by ryankask** [comment]
This should be fixed in https://github.com/django/django/commit/b7d6077517c6cb2daa5e5faf2ae9f94698c06ca9 ([ticket](https://code.djangoproject.com/ticket/28269)). I think will be released in 1.11.3.

**Comment by tredzko** [comment]
@ryankask Good call, it looks like it was included in [1.11.3](https://docs.djangoproject.com/en/1.11/releases/1.11.3/) (Issue #28269), so that should resolve this issue when that is officially released.

**Comment by ryankask** [comment]
[Django 1.11.3 has been released](https://www.djangoproject.com/weblog/2017/jul/01/bugfix-release/) so Django 1.11 users should upgrade. I suppose `install_requires` should exclude the buggy versions as well.
