### ISSUE TITLE
install_requires should include `phonenumbers`

### ISSUE THREAD

**Issue by gogobook** [stefanfoulis/django-phonenumber-field#176]
error code 
```sh
import phonenumbers
ModuleNotFoundError: No module named 'phonenumbers'
```

**Comment by tredzko** [comment]
Per the [setup.py](https://github.com/stefanfoulis/django-phonenumber-field/blob/master/setup.py#L7-L8) code and the [readme](https://github.com/stefanfoulis/django-phonenumber-field#django-phonenumber-field), `phonenumberslite` will be installed unless you install `phonenumbers` yourself.

**Comment by amateja** [comment]
Actually I agree. It was a bad decision to use lite version. We gained almost nothing but there is a huge headache with it. Also a downside of lite version is that it's not a subpackage of phonenumbers but an alternative version which I couldn't even find in their repository. So in my opinion we should switch back and never use lite again till they decide to split their package into several smaller such as e.g.: core, data, etc... and not having alternative wheel just in pypi index.

**Comment by alej0varas** [comment]
I've updated to 1.3.0 and started having this issue. It only happens in my machine but not in my servers :confused:

**Comment by moggers87** [comment]
It should also be noted that the current wheel for phonenumbers lite is still over 2MB (because it contains all the geodata): https://pypi.python.org/pypi/phonenumberslite/8.8.1

`pip` prefers wheel over source distributions, so I doubt anyone is actually installing the stripped down package anyway!

**Comment by stefanfoulis** [comment]
We've dropped the conditional logic in setup.py to use phonenumberslight on the master branch. It will be part of the next release.
