### ISSUE TITLE
[Depreciation] blank=True on modelfield gives integrityError after upgrading from 1.1.0 to 1.3.0

### ISSUE THREAD

**Issue by gabn88** [stefanfoulis/django-phonenumber-field#179]
After upgrading from 1.1.0 to 1.3.0, a model with:

`    phone_number = PhoneNumberField(_("Phone number"), blank=True)`

now gives a IntegrityError after POSTing a form with a empty phone_number. Before, the behaviour was the same as Django's CharField, namely that with blank=True set on the ModelField would INSTERT an empty string ''. This to make sure that no 2 different False values ('' and None/NULL) could exist.

I like the previous behaviour better, but if you want to go with the new behaviour, this should be documented somewhere as it is a breaking change.

**Comment by amateja** [comment]
Hi @gabn88. Thank you for your insight. I'm afraid such change was done on purpose so currently we are not going to change it back. Your remark about proper documentation is sooooo valid though :) (vide #152). We will keep that in mind.

**Comment by gabn88** [comment]
I'm still worried that you did not get my previous comment as this is a big issue.

> from phonenumber_field.modelfields import PhoneNumberField
> 
> class MyModel(models.Model):
>     name = models.CharField(max_length=255)
>     phone_number = PhoneNumberField()
>     fax_number = PhoneNumberField(blank=True)
> Internally, PhoneNumberField is based upon CharField and by default represents the number as a string of an international phonenumber in the database (e.g '+41524204242').
> 
> Representation can be set by PHONENUMBER_DB_FORMAT variable in django settings module. This variable must be one of 'E164', 'INTERNATIONAL', 'NATIONAL' or 'RFC3966'. Recommended is one of the globally meaningful formats 'E164', 'INTERNATIONAL' or 'RFC3966'. 'NATIONAL' format require to set up PHONENUMBER_DEFAULT_REGION variable.
> 
> As with CharField's, it is discouraged to use null=True.

This is literally form the one-page docs and if you do it like this, it does NOT work when entering an empty phone number.

**Comment by shjohnson-pi** [comment]
I just ran into this problem as well.

A workaround is to add `default=''`:
`phone = PhoneNumberField(blank=True, default='')`
