### ISSUE TITLE
Empty strings not rejected when using a ModelSerializer

### ISSUE THREAD

**Issue by ahumeau** [stefanfoulis/django-phonenumber-field#182]
Hi,

I have come across a minor bug when using `django-phonenumber-field` with Django Rest Framework: when creating a `ModelSerializer` for a model that has a required `PhoneNumberField`, the serializer does not reject empty strings.

How to reproduce:

```python
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from rest_framework import serializers


class MyModel(models.Model):
    # A mandatory phone number
    phone_number = PhoneNumberField()
    
    
class MySerializer(serializers.ModelSerializer):
    class Meta:
        model = MyModel
        fields = (
            'phone_number',
        )

MySerializer(data={'phone_number': ''}).is_valid()  # True when it should be False
```

From my understanding, the reason is that Django Rest Framework uses a [`ModelField`](http://www.django-rest-framework.org/api-guide/fields/#modelfield) when it encounters unknown model fields, such a field does not treat the empty string as an empty value whereas `phonenumber_field.phonenumber.to_python` does. So the `ModelField` does not reject `''` and `validate_international_phonenumber` does not either.

A workaround is to use the provided PhoneNumberField serializer field, ex:

```python
from phonenumber_field.serializerfields import PhoneNumberField


class MySerializer(serializers.ModelSerializer):
    phone_number = PhoneNumberField()

    class Meta:
        model = MyModel
        fields = (
            'phone_number',
        )
```

But as everything else works out of the box, people might not realize
that they need to.

**Comment by lalzada** [comment]
Same here. Not validating integers as well `12121` instead of `"12121"` throws error when passing non quoted integers

**Comment by lalzada** [comment]
work around found [here](https://github.com/stefanfoulis/django-phonenumber-field/issues/72#issuecomment-199917369)

**Comment by Gathondu** [comment]
@ahumeau thanks for this work around.

**Comment by lalzada** [comment]
This is already implemented in this package. Give a look (here)[https://github.com/stefanfoulis/django-phonenumber-field/blob/master/phonenumber_field/serializerfields.py#L11]
