### ISSUE TITLE
widgets module not importable

### ISSUE THREAD

**Issue by lepetitchevalblanc** [stefanfoulis/django-phonenumber-field#183]
I've tried to use the PhoneNumberPrefixWidget from phonenumber_field.widgets module but I could not manage to import it. I've also tried from a python shell, with no success. File is installed in phonumber_field directory in the site-packages of my virtualenv.

What I miss here ?

Thx

**Comment by iYalovoy** [comment]
from phonenumber_field.widgets import PhoneNumberPrefixWidget
phone = PhoneNumberField(label=_("Phone"), widget = PhoneNumberPrefixWidget)

This works for me!

**Comment by stefanfoulis** [comment]
I'm closing this for now. Please re-open if still needed.
