### ISSUE TITLE
templatetag for rendering phone number fields

### ISSUE THREAD

**Issue by danni** [stefanfoulis/django-phonenumber-field#186]
It would be great to have a template tag that replicated the behaviour of `PhoneNumberInternationalFallbackWidget`

**Comment by amateja** [comment]
I see no reason why we shouldn't do that. Especially the required part of code is at least partially there. You have unique chance to define your request more thoroughly if you like @danni 😉.

**Comment by danni** [comment]
What I've done currently is pulled the code from `PhoneNumberInternationalFallbackWidget`, which met my needs.

**Comment by bartmika** [comment]
+1

**Comment by RaddishIoW** [comment]
+1

**Comment by typonaut** [comment]
I've had a go at a template tag, perhaps someone could add it to the source, or correct it.

```./phonenumber_field/templatetags/phonenumber_tags.py```

```
from django.conf import settings
from django import template

from phonenumbers import PhoneNumberFormat
from phonenumbers.phonenumberutil import region_code_for_number
from phonenumber_field.phonenumber import PhoneNumber

register = template.Library()

@register.filter(name='pn_ifallback')
def pn_ifallback(value):

    """
        A filter to display phone numbers in the same format as displayed
        using the PhoneNumberInternationalFallbackWidget on a form.
        
        Usage:
        
            {{ template.var|pn_ifallback }}
    """
    
    region = getattr(settings, "PHONENUMBER_DEFAULT_REGION", None)

    if isinstance(value, PhoneNumber):
        number_region = region_code_for_number(value)
        if region != number_region:
            formatter = PhoneNumberFormat.INTERNATIONAL
        else:
            formatter = PhoneNumberFormat.NATIONAL
        return value.format_as(formatter)
    else:
        return value
```

**Comment by philippeowagner** [comment]
I'm using ^^ [phonenumber_tags.py](https://github.com/stefanfoulis/django-phonenumber-field/issues/186#issuecomment-726752515). Works great. Would be nice to have it included.

**Comment by francoisfreitag** [comment]
Requested feature should be handled since https://github.com/stefanfoulis/django-phonenumber-field/commit/005769cf39323e5b23710783f45befb546672cd6. Note that the implementation is being improved in https://github.com/stefanfoulis/django-phonenumber-field/pull/520.
