### ISSUE TITLE
`KeyError` when trying to access PhoneNumberField in receiver in Django 1.10

### ISSUE THREAD

**Issue by Nizebulous** [stefanfoulis/django-phonenumber-field#187]
I'm using Django 1.10.

I have a `post_save` receiver that is trying to access the `PhoneNumberField` on an object. When I try to  run the code (that was working in Django 1.9), I get a `KeyError` in the `__get__` method in the `PhoneNumberDescriptor`. Specifically this is happening during object creation.

The field does not appear to be available yet.

Note that the field is `blank=True` and `null=True`.

**Comment by stefanfoulis** [comment]
I'm closing this for now, as we've dropped support for Django<=1.11.3. Please re-open if the problem still exists in supported Django versions.
