### ISSUE TITLE
Django 2.0 support: _format_value renamed, maybe more

### ISSUE THREAD

**Issue by jodal** [stefanfoulis/django-phonenumber-field#193]
Django 2.0 is slated for release in about a month and django-phonenumber-field should work with it.

As far as I know, django-phonenumber-field uses at least one feature that had a breaking change in Django 2.0: [Widget.format_value](https://docs.djangoproject.com/en/1.11/ref/forms/widgets/#django.forms.Widget.format_value) has been renamed from `_format_value` to `format_value` to make it a part of the public API.

The CI test matrix is growing quite large, and with the addition of Python 3.6 and Django 2.0 it will become even larger. Django upstream suggests to drop support for anything older than 1.11 LTS and make sure the project runs on 1.11 without any warnings. Then it should work on 2.x as well without changes. I'll leave to the project maintainers to decide if the list of Django versions supported by django-phonenumber-field should be pruned a bit.

**Comment by benkonrath** [comment]
I'm also interested in seeing django-phonenumber-field support Django 2.0. We're planning to remove the phone number fields from django-localflavor for our Django 2.0 compatible release and we're specifically recommending django-phonenumber-field and an alternative. Are there any plans for the Django 2.0 compatible release of this library?

**Comment by jodal** [comment]
Django 2.0 have now been released. A new release of django-phonenumber-field that works with Django 2.0 would be lovely :-)

**Comment by stefanfoulis** [comment]
I probably won't have time to look into Django 2.0 support in the next few weeks. PRs are very welcome :-)

**Comment by benkonrath** [comment]
@stefanfoulis Any chance you can take a look at the PR for this? #196

**Comment by stefanfoulis** [comment]
thanks @benkonrath. I’ll have a look soon.

**Comment by jodal** [comment]
Thank you, @benkonrath and @stefanfoulis :-)
