### ISSUE TITLE
Emulate behavior of Google's phonenumber field

### ISSUE THREAD

**Issue by jrief** [stefanfoulis/django-phonenumber-field#195]
Some people have difficulties using their country prefix, since they are used to only enter their national number without, say *+49*. Google does a pretty good job in this respect. Simply access your Google account, go to *My personal data*, look for your phonenumber field and edit it.

![screen shot 2017-11-23 at 15 34 23](https://user-images.githubusercontent.com/1132472/33514477-e32d043a-d754-11e7-96d2-a8d23da9e033.png)

By using a select box together with an input field, the UX is much better than by a single input field itself. The database field would not be affected by this change, only the phone number form field would then be made up out of two widgets.

![screen shot 2017-12-02 at 11 45 43](https://user-images.githubusercontent.com/1132472/33514564-634fb2d8-d756-11e7-95e3-92d6ed14e3f5.png)

If this proposal is accepted, I can implement it.

**Comment by stefanfoulis** [comment]
That would be very cool :-)

Would you implement it with the flags? (where would the flag graphics come from?)
Would this be a new FormField? (so it is a deliberate choice of the developer to use the new and more awesome field. Or should everyone just get the new widget. Devs who have custom styling in their project might run into problems if we add another input to the html.)

**Comment by jrief** [comment]
Hi Stefan,

> Would you implement it with the flags? (where would the flag graphics come from?)

yes, I would use a png-sprite with some css. There are plenty of flags available on Github under a compatible license.

> Would this be a new FormField? (so it is a deliberate choice of the developer to use the new and more awesome field.

I would leave the model field as is, and just add a new widget to the existing form field. To implement it, I would use Django's [MultiWidget](https://docs.djangoproject.com/en/stable/ref/forms/widgets/#multiwidget) as the base class. This then can easily be overridden by a normal Text- or RegexField.

**Comment by danielMicallef** [comment]
Has this been implemented @jrief ? This is very useful!

**Comment by jrief** [comment]
@danielMicallef not yet, because that feature request was removed from the project I was working on. If you need that feature, please contact me on my private email address.

**Comment by jrief** [comment]
Currently, **django-phonenumber-field** is shipped with a widget named `PhoneNumberPrefixWidget`, which inherits from Django's `MultiWidget`. There, the phone number is split into an international prefix and the national part. From a UX point of view, this is not very satisfying, because users often want to copy and paste their full phone number into the input field.

Therefore, I would create a similar widget, say `PhoneNumberWidget` inheriting from Django's `MultiWidget`. This widget is composed as well, of a `Select` and a `TextInput` widget. The `Select` widget renders flags, country names and the international prefix. The `TextInput` accepts the full phone number, for example `+49891234567`, just as the existing `PhoneNumberInternationalFallbackWidget` does.

To emulate the behaviour of Google's phone number input, JavaScript shall be used. This script triggers an event, whenever the `<select...>` or the `<input...>` element changes and it updates the other sibling widget accordingly. To avoid external dependencies, I would prefer pure ES5 without any JS framework.

**Comment by wisefool769** [comment]
@stefanfoulis I'm guessing there's no ETA on this, right? 
I'm very interested in this functionality. @jrief if you push a partial solution somewhere, maybe someone else can take a crack at submitting a PR.

**Comment by jrief** [comment]
@wisefool769 if you want to implement it yourself, I can give you some advise. Currently this feature request is not high on my priority list, so nothing has been implemented yet. If you don't have the time to implement it yourself but want to fund this feature, please contact my on my private email address.

**Comment by francoisfreitag** [comment]
The suggested behavior requires some JavaScript and static assets, which makes it harder to integrate the app in projects pipelines. In order to service users without JavaScript, a fallback would also need to be implemented.

Providing a widget that makes it reasonably simple to select a phone number from supported countries is enough. Projects can implement their phone number field with all the bells and whistles that fits their requirements, but let’s keep this project just Django.

**Comment by jrief** [comment]
@francoisfreitag @stefanfoulis this has been implemented outside of django-phonenumber-field, here is a demo:
https://django-formset.fly.dev/phone-number-field/

**Comment by dsapattern-web** [comment]
> [@francoisfreitag](https://github.com/francoisfreitag) [@stefanfoulis](https://github.com/stefanfoulis) this has been implemented outside of django-phonenumber-field, here is a demo: https://django-formset.fly.dev/phone-number-field/

Hey, I'm trying to adapt this to my code but my phone number box just appears empty. Do you know if the documentation is still up to date? And if so, do you have a full working example I can get reference?

**Comment by jrief** [comment]
@dsapattern-web which documentation do you mean? That for django-formset or for django-phonenumber-field?

**Comment by dsapattern-web** [comment]
@jrief I meant that for Phone Number Field, but I seems like to adapt django-formset to my form somehow.
