### ISSUE TITLE
Is there a way to check whether a phone number is valid?

### ISSUE THREAD

**Issue by michaelhjulskov** [stefanfoulis/django-phonenumber-field#201]
Hi
Thanks sharing for this :)

I am looking for at way to validate if a number is valid, before I save it.
inside my view I would like to do something like this:

`from phonenumber_field.validators import validate_international_phonenumber`
`phone_number = "+32312312321"`
`if phone_number and validate_international_phonenumber(phone_number):`
`...`

How is this acheived, using django-phonenumber-field ?

Thank You :)

**Comment by michaelhjulskov** [comment]
i have found the below temp fix, but I still would prefer to use this django-phone-number to validate, so its the same validation.

temp fix:
VALID_PHONE_NUMBER_REGEX = "^+(9[976]\d|8[987530]\d|6[987]\d|5[90]\d|42\d|3[875]\d|2[98654321]\d|9[8543210]|8[6421]|6[6543210]|5[87654321]|4[987654310]|3[9643210]|2[70]|7|1)\d{1,14}$"
phone_number = "+3323232332"
if re.match(VALID_PHONE_NUMBER_REGEX, phone_number):
  print "valid"

**Comment by lampslave** [comment]
https://github.com/stefanfoulis/django-phonenumber-field/blob/cf584dd2e54000ec85edf4717d0142aeb77109d2/phonenumber_field/phonenumber.py#L44

**Comment by michaelhjulskov** [comment]
Thanks You for pointing me to the relevant function. 
So would this work?

from phonenumber_field.phonenumber import PhoneNumber
if phone_number and PhoneNumber.is_valid(phone_number):

**Comment by michaelhjulskov** [comment]
Thanks You for pointing me to the relevant function.
So something like this is correct?

from phonenumber_field import phonenumber
if phonenumber.PhoneNumber.is_valid(phonenumber.to_python(phone_number)):

**Comment by stefanfoulis** [comment]
@michaelhjulskov did you find a solution that works for you?
I'll close this issue for now. Please re-open if still needed.
