### ISSUE TITLE
Phone number extensions?

### ISSUE THREAD

**Issue by epicserve** [stefanfoulis/django-phonenumber-field#205]
I'm not seeing anything in the readme about phone number extensions. I'm currently getting an exception error when a user tries to enter an extension (e.g. 800-555-1212 ex. 1234). There should probably be something in the readme about how to handle extensions. Also, the code should be updated to either give the user a soft error instead throwing the exception, "DataError: Data too long for column 'contact_phone' at row 1" or the code should be updated so that you can save a phone number with an extension.

**Comment by stefanfoulis** [comment]
Thanks for reporting

**Comment by epicserve** [comment]
I think it would be nicest if the extension was stored in the phone number field so you don't have to add another field to your model for the extension.

**Comment by epicserve** [comment]
BTW, when you look at https://contacts.google.com/. Google lets you put the ex. in the same field. I have not way of knowing that's how they store it on the backend though. But it seems reasonable to think they would store it in one field.

**Comment by Dunedan** [comment]
As I'm facing the same issue, that I want to be able to support phone numbers with extensions, I dug a bit into it. I believe the reason for the current behavior is that E.164 is all about _public_ phone numbers and extensions aren't considered to be a part of public phone numbers. Therefore E.164 simply doesn't cover extensions. While `libphonenumber` and `python-phonenumbers` in general support extensions, as E.164 is used as the default format for storing and displaying phone numbers by  `django-phonenumber-field`, the extension is simply stripped when storing a phone number and even if it would get stored, it wouldn't be displayed. While I have no real solution for that, I believe changing the storage and display formats for phone numbers to E.123 international format can be quite a good workaround, as E.123 supports extensions.

Fortunately `django-phonenumber-field` already supports using different formats than E.164 for storing and displaying phone numbers, so configuring this is pretty straight forward using the following configuration options:

```python
PHONENUMBER_DEFAULT_FORMAT = "INTERNATIONAL"
PHONENUMBER_DB_FORMAT = "INTERNATIONAL"
```

**Comment by ryanovas** [comment]
+1 for handling extensions
