### ISSUE TITLE
Add PHONENUMBER_DB_FORMAT example and default value in README.rst

### ISSUE THREAD

**Issue by oza4h07** [stefanfoulis/django-phonenumber-field#207]
Hello,

I'm both discovering Django and django-phonenumber-field.

1. Would it possible to add in README.rst, an example on how to set PHONENUMBER_DB_FORMAT ?
This would be very valuable for those like me, that are not yet fluent with Django's settings files.
In my opinion, there is no need to cover all options : a single working one would be enough.

2. README.rst includes "Recommended is one of the globally meaningful formats" but does not say PHONENUMBER_DB_FORMAT is used when no one is set. Did I miss something ?

Best regards

**Comment by kelvinromero** [comment]
Totally lost on that too. If you have found something, please do a follow up!

**Comment by Quayle57** [comment]
I'm late but in your settings just put something like :

```python
PHONENUMBER_DB_FORMAT = 'NATIONAL'
PHONENUMBER_DEFAULT_REGION = 'FR'
```

This will work for french number like `0312345678` and `+33123456789`

I tried the default region code but from what I understood, `PHONENUMBER_DB_FORMAT` is a string like in the readme, I would have liked for it to be an array/tuple and pass `NATIONAL` and `INTERNATIONAL` at the same time but I don't know if it's possible.
