### ISSUE TITLE
Localize phone number according to locale habits

### ISSUE THREAD

**Issue by frague59** [stefanfoulis/django-phonenumber-field#208]
Hi, 

Here, in France, we use to display (local) phone numbers with 2 digits:

Example: 06 XX XX XX XX (for a mobile phone number)

Is it a simple way to format such phone numbers directly in the templates ?
If not, I think using a `{{ phone_number|localize }}` should be a good API...

Thanks !

**Comment by ls-initiatives** [comment]
Adding this to `settings.py` should be enough, shouldn't it:
```
PHONENUMBER_DEFAULT_FORMAT = 'NATIONAL'
PHONENUMBER_DEFAULT_REGION = 'FR'
```

**Comment by francoisfreitag** [comment]
When the field has a region set (see `PHONENUMBER_DEFAULT_REGION` for a way to set that globally), the local phone numbers will display in the region’s format. Other will use the configured `PHONENUMBER_DEFAULT_FORMAT`.
