### ISSUE TITLE
Default Country Code?

### ISSUE THREAD

**Issue by CT83** [stefanfoulis/django-phonenumber-field#218]
Is there a way append a default country code? If no Country code is typed?
I am thinking along the lines of, 
`mobile = PhoneNumberField(required=True, country='india')`
or
`mobile = PhoneNumberField(required=True, country='+91')`
My users are not smart enough to add their own country code, sometimes. It raises few errors. I currently tell them add the country code in a html placeholder.

**Comment by stefanfoulis** [comment]
hmm... Maybe a ``default_country_code`` that is automatically appended if the user does not enter a country code?

**Comment by iuyoy** [comment]
HI @CT83,  I think you can add this config `PHONENUMBER_DEFAULT_REGION = "IN"` in `settings.py`.

**Comment by lalzada** [comment]
@iuyoy i am using `PHONENUMBER_DEFAULT_REGION = "US"` but when i try to save phone number with country code say `+92`, it doesn't raise validation error as i have set region to US and should accept `+1` only. It replaces `+92` with `+1` in db but doesn't raise validation error before saving.. I am using serializers phone number field on my serializer as well.

**Comment by iuyoy** [comment]
@lalzada, It's strange, when I input numbers with other country code in my application, it will be stored as the original input, not `+1`,  without any validation.
To solve your problem, I think, you can do some more checks on that field. You can find some useful information in [python-phonenumbers](https://github.com/daviddrysdale/python-phonenumbers) which is a plugin this project used.

**Comment by francoisfreitag** [comment]
I'm not sure I understand your issue, but perhaps customizing the default country code at the field level as suggested in https://github.com/stefanfoulis/django-phonenumber-field/pull/263 would help?

**Comment by sandeepimpressads** [comment]
@francoisfreitag seems it is not merged to master yet.

**Comment by francoisfreitag** [comment]
I see the PR was merged with 99713a846d3c5632ffcc214d9de28cb9c9e30813, and included in releases since 2.3.0?

**Comment by sandeepimpressads** [comment]
> I see the PR was merged with [99713a8](https://github.com/stefanfoulis/django-phonenumber-field/commit/99713a846d3c5632ffcc214d9de28cb9c9e30813), and included in releases since 2.3.0?
tried with a field `PhoneNumberField(region="IN") ` thought it will show a validation error from form that the entered phone number is not Indian. But when I tried with a UK number with +44, the form simply saved the details. No validation error appeared. I wanted to allow the phone numbers belonging to that country only when the region is set in the PhoneNumberField.

**Comment by francoisfreitag** [comment]
Passing a region is not meant to restrict phone numbers to a given region, it is meant to interpret regional phone number input in the context of a specified region. It is not meant to force users to have a phone number in the given region.

For example, North American phone numbers are usually written `6044011234`. That number only works for people calling from the North America, it is regional. To call it from another place in the world, one has to prefix it with `+1`, so that it reads `+16044011234`. In other regions in the world, `6044011234` may reach a different phone in that region.
Setting the default region allows interpreting `6044011234` as `+16044011234`, uniquely identifying the phone number.

To implement your use case, you could create a validator that checks the phone number country code, e.g.:

```pycon
>>> import phonenumber
>>> z = phonenumbers.parse('+33612345678')
>>> z.country_code
33  # France.
```

**Comment by sandeepimpressads** [comment]
> Passing a region is not meant to restrict phone numbers to a given region, it is meant to interpret regional phone number input in the context of a specified region. It is not meant to force users to have a phone number in the given region.
> 
> For example, North American phone numbers are usually written `6044011234`. That number only works for people calling from the North America, it is regional. To call it from another place in the world, one has to prefix it with `+1`, so that it reads `+16044011234`. In other regions in the world, `6044011234` may reach a different phone in that region.
> Setting the default region allows interpreting `6044011234` as `+16044011234`, uniquely identifying the phone number.
> 
> To implement your use case, you could create a validator that checks the phone number country code, e.g.:
> 
> ```
> >>> import phonenumber
> >>> z = phonenumbers.parse('+33612345678')
> >>> z.country_code
> 33  # France.
> ```

Thanks for the detailed info. Where do i write the validator ? Is it possible by overriding a form from the package ?

**Comment by francoisfreitag** [comment]
You’ll probably find https://docs.djangoproject.com/en/3.0/ref/forms/validation/#using-validation-in-practice useful.
