### ISSUE TITLE
serializerfields.PhoneNumberField always needs required=False even if using blank=True

### ISSUE THREAD

**Issue by estianross** [stefanfoulis/django-phonenumber-field#222]
Since internal type is CharField setting blank=True on modelfields.PhoneNumberField should make that field not required in the serializer yet I still have to specify required=False on the serializer field or else it errors out with ErrorDetail(string='This field is required.', code='required'). Not really a huge deal but this is not expected behaviour if internal type is CharField

**Comment by francoisfreitag** [comment]
I believe this is no longer the case. https://github.com/stefanfoulis/django-phonenumber-field/pull/524
