### ISSUE TITLE
Serialization

### ISSUE THREAD

**Issue by jerryshikanga** [stefanfoulis/django-phonenumber-field#225]
The modelfield is not JSON serializable out fo the box. Custom solutions have to be used to make it so or else it raises an error as below 👍 :
```
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PhoneNumber is not JSON serializable
```
Suggest it is implemented out of the box for use with [Django Rest Framework](http://www.django-rest-framework.org/).

**Comment by stefanfoulis** [comment]
I agree. It should just work out of the box with django rest framework.

**Comment by bukowa** [comment]
What is your current solution?

**Comment by ameya-amazatic** [comment]
Does anyone found a solution for this?

**Comment by jdufresne** [comment]
The project comes with a DRF field. Are you able to use it for you needs?

https://github.com/stefanfoulis/django-phonenumber-field/blob/master/phonenumber_field/serializerfields.py

**Comment by emilgeorgejames1** [comment]
import from serializerfields

```
from phonenumber_field.serializerfields import PhoneNumberField

class SignupSerializer(serializers.Serializer):
    mobile_number = PhoneNumberField()
```

**Comment by cgthayer** [comment]
I would like to see this work more broadly, but I think it's difficult because a PhoneNumber object may be incomplete or incorrect (meaning not a valid phone number).  I use a separate wrapper class to manage the "user version" (raw input text) and the phone object, which supports some normalization and validation checks.

more about custom json encoding here: https://stackoverflow.com/questions/18478287/making-object%20-json-serializable-with-regular-encoder

**Comment by shahwan42** [comment]
I'm facing the same issue when I get the `serializer.valdiated_data` and try to dump it as JSON...
PhoneNumber class has to be JSON-serializable

**Comment by olek5andr** [comment]
> I would like to see this work more broadly, but I think it's difficult because a PhoneNumber object may be incomplete or incorrect (meaning not a valid phone number). I use a separate wrapper class to manage the "user version" (raw input text) and the phone object, which supports some normalization and validation checks.
> 
> more about custom json encoding here: https://stackoverflow.com/questions/18478287/making-object%20-json-serializable-with-regular-encoder

Could you please provide an example code of how you have solved the issue?

**Comment by tanwirahmad** [comment]
I fixed it like this:

```
class PhoneNumberFieldSerializable(PhoneNumberField):

    def to_internal_value(self, data):
        phone_number = to_python(data)
        if phone_number and not phone_number.is_valid():
            raise ValidationError(self.error_messages["invalid"])
        return phone_number.as_e164
```

**Comment by shahwan42** [comment]
@tanwirahmad from where do you import `to_python`?

**Comment by shahwan42** [comment]
Thank you @tanwirahmad 

Here's the complete solution that worked for me

```Python
from rest_framework.serializers import ValidationError
from phonenumber_field.serializerfields import PhoneNumberField
from phonenumber_field.phonenumber import to_python


class CustomPhoneNumberField(PhoneNumberField):
    def to_internal_value(self, data):
        phone_number = to_python(data)
        if phone_number and not phone_number.is_valid():
            raise ValidationError(self.error_messages["invalid"])
        return phone_number.as_e164
```

**Comment by kohlab** [comment]
What's the upshot of this thread? Will @shahwan42's fix be merged into the release branch? What do folks recommend?

**Comment by rudneff13** [comment]
Hey, guys, let me share my thoughts... I'm trying to pass invalid value to serializerfields.PhoneNumberField and I expect to get ValidationError. But instead I get TypeError, because "to_python" can't convert int to PhoneNumber. Why is it so: TypeError instead of ValidationError?

**Comment by pendolf** [comment]
It's should support formating, like this `phone_number = PhoneNumberField(format='e164')`


```python
from django.utils.translation import gettext_lazy as _
from rest_framework import serializers
from rest_framework.exceptions import ValidationError

from phonenumber_field.phonenumber import to_python


class PhoneNumberField(serializers.CharField):
    valid_formats = ('international', 'e164', 'national', 'rfc3966')
    default_error_messages = {"invalid": _("Enter a valid phone number.")}

    def __init__(self, **kwargs):
        self.phone_number_format = kwargs.pop('format', 'e164')
        if self.phone_number_format not in self.valid_formats:
            raise ValueError(
                'Invalid format for phone number representation. '
                'Must be one of "{}"'.format('", "'.join(self.valid_formats))
            )
        super().__init__(**kwargs)

    def to_internal_value(self, data):
        phone_number = to_python(data)
        if phone_number and not phone_number.is_valid():
            raise ValidationError(self.error_messages["invalid"])
        return phone_number

    def to_representation(self, value):
        return getattr(value, 'as_' + self.phone_number_format)
```

**Comment by francoisfreitag** [comment]
This issue seems to be a collection of problems people encountered over the years by using rest_framework with this library. If does not seem to have an issue in particular that needs addressing.
