### ISSUE TITLE
Validate phone numbers in form field

### ISSUE THREAD

**Issue by michelle2905** [stefanfoulis/django-phonenumber-field#232]
Hi, I am new to Django. I have created a contact form on my home page, and used the PhoneNumberField coupled with PhoneNumberPrefixWidget in my ModelForm. As I want this field to be mandatory, I did not specify required = False. As a result, user is prompted by "Fill out this field" if field is left blank (which is good). My issue is if user enters gibberish, say 'help', and clicks on submit the page will reload and scroll back to top. Even if you scroll back down to the form, there is no specific indication that there was an error with the phone number entry. Is there something that I am doing wrong? Shouldn't the validation return "Number is invalid" error message?

_model.py_
class Contact(models.Model):
    phone_number = PhoneNumberField()

_form.py_
class ContactForm(forms.ModelForm):
    phone_number = PhoneNumberField(widget=PhoneNumberPrefixWidget(attrs={'placeholder':'Phone Number'}), initial='+65')

_html_
<form method="post">
  {% csrf_token %}
  {{ form.phone_number errors }} 
  {{ form. phone_number }}
....
</form>

**Comment by michelle2905** [comment]
Released that I did not include "django.core.exceptions import ValidationError" in my forms.py

**Comment by shawnngtq** [comment]
@michelle2905 , I am facing similar issue, from your code snippet, I don't see how `ValidationError` is used, can you explain / give more detail about your solution 😁
