### ISSUE TITLE
v2.1.0 is broken

### ISSUE THREAD

**Issue by Fandekasp** [stefanfoulis/django-phonenumber-field#242]
upgraded the package from 2.0.1 to 2.1.0, and my system crashed with the following error

```py
backend_1         |   File "/code/app/models/user.py", line 5, in <module>
backend_1         |     from phonenumber_field.modelfields import PhoneNumberField
backend_1         |   File "/usr/local/lib/python3.7/site-packages/phonenumber_field/modelfields.py", line 8, in <module>                                                             
backend_1         |     from phonenumber_field import formfields
backend_1         |   File "/usr/local/lib/python3.7/site-packages/phonenumber_field/formfields.py", line 7, in <module>                                                              
backend_1         |     from phonenumber_field.phonenumber import to_python
backend_1         |   File "/usr/local/lib/python3.7/site-packages/phonenumber_field/phonenumber.py", line 6, in <module>                                                             
backend_1         |     import phonenumbers
backend_1         | ModuleNotFoundError: No module named 'phonenumbers'
```

Bug occurs in `phonenumber_field/formfields.py`.
Package worked fine up to v2.0.1. Strange that the unit test suite didn't catch this import issue.

**Comment by stefanfoulis** [comment]
@Fandekasp exactly. You need to install either `phonenumbers` or `phonenumberslite` alongside the package. See the installation instructions in README.rst and the note in CHANGELOG.rst for further information.

**Comment by jcass77** [comment]
@Fandekasp, are you reporting a version number incompatibility between ``django-phonenumber-field`` and ``phonenumbers`` / ``phonenumberslite ``?

If so, then we probably need to bump the required version numbers in [setup.py](https://github.com/stefanfoulis/django-phonenumber-field/blob/870b3826fa159c732f8a2036e47393c2cb9654fd/setup.py#L18-L19).

**Comment by Fandekasp** [comment]
@stefanfoulis 	I see, thanks for the reply. I indeed went too fast over the release notes.

It would be great if you could follow semantic versioning recommendations: Since this upgrade included breaking changes, a major release would have made sense. Else, writting "BREAKING CHANGE" in uppercase in the release notes would make it harder to miss ^^

Thanks again!
cheers
