### ISSUE TITLE
PhoneNumberField Not Working With Serializer

### ISSUE THREAD

**Issue by bobozar** [stefanfoulis/django-phonenumber-field#246]
I tried using PhoneNumberField in django rest framework but it's not working. I keep getting the error, 

```
{
    "message": "reciever_phone: Enter a valid phone number. ",
    "status_code": 400
}
```
I supplied the field with `reciever_phone='+278128264425'`

```
from phonenumber_field.serializerfields import PhoneNumberField

class TxSerializer(serializers.ModelSerializer):
         reciever_phone = PhoneNumberField(required=True)
```

What is Wrong?

**Comment by apenab** [comment]
From [libphonenumber.appspot.com](https://libphonenumber.appspot.com/phonenumberparser?number=%2B278128264425)

![image](https://user-images.githubusercontent.com/22795807/79606616-b81c2480-80a6-11ea-825c-16e8bc9ba903.png)
