### ISSUE TITLE
Running migration results in AttributeError

### ISSUE THREAD

**Issue by cidylle** [stefanfoulis/django-phonenumber-field#247]
Currently running migration on `phonenumber_field` results in the following attribute error:
```AttributeError: module 'phonenumbers' has no attribute 'PhoneNumber'```

Django 2.1.3
Python 3.7.0

**Comment by stefanfoulis** [comment]
@cidylle does the error show in which migration the exception happens?

**Comment by cidylle** [comment]
@stefanfoulis Unfortunately I could not see that information anywhere in the stack printout. I'll try to find out more. Just wanted to make sure it's just me and not a wider spread issue.

**Comment by i12maroa** [comment]
Same Problem here

**Comment by jdufresne** [comment]
To me, this looks like an error in how the [phonenumbers](https://pypi.org/project/phonenumbers/) package was installed. If you still believe this is an issue with django-phonenumber-field, please provide additional details and explanation.
