### ISSUE TITLE
How to set instanceA.phone_number = instanceB.phone_number

### ISSUE THREAD

**Issue by FeatherZhong** [stefanfoulis/django-phonenumber-field#249]
Hi am trying to set instanceA.phone_number = instanceB.phone_number but it return
 `TypeError PhoneNumber(.....) is not JSON serializable`
What should i do to set A.phone_number =B.phone_number or how can i get conver phone_number into string

**Comment by stefanfoulis** [comment]
That looks like a bug, that kind of assignment should be possible.

As a workaround the string representation should work:

```
instanceA.phone_number = str(instanceB.phone_number)
```

**Comment by FeatherZhong** [comment]
Thanks a lot , i find the mistake was actually made elsewhere
--that I am trying to Response  instanceA.phone_number directly
Sorry for that
