### ISSUE TITLE
serializerfields.PhoneNumberField not validating int number correctly

### ISSUE THREAD

**Issue by dionysio** [stefanfoulis/django-phonenumber-field#265]
I have a serializer:
```
class MySerializer(Serializer):
    phone = PhoneNumberField(required=True)
```

and in my view:
```
serializer = MySerializer(data=request.data)
if serializer.is_valid():
    phone = serializer.validated_data['phone'].as_e164
```

This doesn't work if I pass `phone=15417543010` (int number). In that case, it passes validation, but `serializer.validated_data['phone']` will be `None`.

**Comment by vjMagar** [comment]
Hi @dionysio, 

Have you tried using string instead of int in the above case?

**Comment by dionysio** [comment]
yep, it works fine with strings

**Comment by Alig1493** [comment]
the phonenumber filed **[here](https://github.com/stefanfoulis/django-phonenumber-field/blob/master/phonenumber_field/serializerfields.py#L11)** according to the to_python logic **[here](https://github.com/stefanfoulis/django-phonenumber-field/blob/master/phonenumber_field/phonenumber.py#L109)** should raise a type error in case it is unable to parse and give back results. It checks for the phone number of type str and phonenumber type instance for now. I can take a look at this further and f course I might be missing valuable context in my insight.
