### ISSUE TITLE
Add manual field gives attribute error

### ISSUE THREAD

**Issue by fawolfmann** [stefanfoulis/django-phonenumber-field#287]
I modify a model adding PhoneNumberField and for the existing rows I add any number, 
so when I want to migrate gives this error:
 ``` [bash]
File "/home/.local/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 785, in get_db_prep_value 
value = self.get_prep_value(value) 
File "/home/.local/lib/python3.6/site-packages/phonenumber_field/modelfields.py", line 74, in get_prep_value
if value.is_valid():
AttributeError: 'NoneType' object has no attribute 'is_valid'  
 ```

this was my field:
 ``` [python]
phone_number = models.IntegerField()
 ```

this is what i change: 
 ``` [python]
phone_number = PhoneNumberField()
 ```

but when i comment this lines gives me the same error

**Comment by stefanfoulis** [comment]
If you look at the database now, what kind of data is in the phone_number field and of which type is it at database level?
I suspect the database contains invalid values now which `PhoneNumberField` can't handle.

**Comment by fawolfmann** [comment]
So i delete the db, it has just a few rows.
migrate again and again the same issue

in the db the field is:  "phone_number" varchar(128) NOT NULL

**Comment by ctohster** [comment]
I get the same thing

**Comment by adamyala** [comment]
I got the same error.

My model looks like:
```
from phonenumber_field import modelfields as phone_number_models
... some-class-declaration-here ...
phone_number = phone_number_models.PhoneNumberField(null=False, blank=False)
```

The auto-generated migration was:
```
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=5555555555, max_length=128, region=None),
            preserve_default=False,
        ),
```
The problem line was:
```
field=phonenumber_field.modelfields.PhoneNumberField(default=5555555555, max_length=128, region=None),
```
I had to change the `default` from an integer to a string like:
```
field=phonenumber_field.modelfields.PhoneNumberField(default='555-555-5555', max_length=128, region=None),
```

**Comment by jdufresne** [comment]
Where did `default=5555555555` come from? Did you enter this value as the default when asked by Django?

**Comment by adamyala** [comment]
@jdufresne Yes! I apologize for not mentioning that. `default=5555555555` came from me entering `5555555555` as the default value when prompted at migration creation.

**Comment by jdufresne** [comment]
Thanks! Then I believe this is not a bug. It is up to you to enter a useful value when Django prompts. If an unusable value is entered, it makes sense that there will be a failure.

If you still believe this fault of djano-phonenumber-field, please provide additional information and explanation.
