### ISSUE TITLE
Phone numbers not persisted to database

### ISSUE THREAD

**Issue by simonschmidt** [stefanfoulis/django-phonenumber-field#289]
```
x = models.Example.objects.create(phone_number='+1234567')
x.phone_number
# Out: PhoneNumber(country_code=1, ...)

x.refresh_from_db()
x.phone_number
# Out: ''
```

The model is simply:

```
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

class Example(models.Model):
    phone_number = PhoneNumberField()
```

With:
Django==2.2
django-phonenumber-field==2.3.1
phonenumberslite==8.10.9

**Comment by simonschmidt** [comment]
Seems to only happen with invalid phone numbers, I'm quite surprised that it doesn't complain and just silently discards the data

**Comment by amateja** [comment]
Might be related to #273.

**Comment by jdufresne** [comment]
Thanks for the report.

Is this a change in behavior that broke with the most recent release? Was was the behavior you experienced before version 2.3.0?

**Comment by jakedahn** [comment]
I ran into this bug this morning while trying to add django-phonenumber-field to a new django 2.2 app. I haven't used django-phonenumber-field before, but I can confirm that the latest release is broken.

For what it's worth the phone number is actually being persisted to the database, it just doesn't contain a country code prefix.

Expected: When I save "+11231231234" it should be persisted to the database as "+1 (123) 123-1234"
Actual: When I try to save "+11231231234" the actual value in the database gets persisted as "(123) 123-1234"

If I manually go into the database and update the column value with a `+1` prefix, things return to working as expected

---

Here's some output from a django shell that might be helpful:

```
ipdb> user = get_user_model().objects.get(id=1)
ipdb> user.unverified_phone_number = "+11231231234"
ipdb> user.save()

# NOTE: I believe this value is cached in the instance of the user object
ipdb> user.unverified_phone_number
PhoneNumber(country_code=1, national_number=1231231234, extension=None, italian_leading_zero=None, number_of_leading_zeros=None, country_code_source=1, preferred_domestic_carrier_code=None)

# NOTE: This is loading a fresh query from the db
ipdb> get_user_model().objects.get(id=1).unverified_phone_number
''
```

After I manually update the value in the DB from `(123) 123-1234` to `+1(123) 123-1234` things appear to work as expected:

```
get_user_model().objects.get(id=1).unverified_phone_number
PhoneNumber(country_code=1, national_number=1231231234, extension=None, italian_leading_zero=None, number_of_leading_zeros=None, country_code_source=1, preferred_domestic_carrier_code=None)
```

I hope this helps!

**Comment by jakedahn** [comment]
I believe I just discovered the root cause; at least for my problem.

When I was playing around I set the settings value of `PHONENUMBER_DB_FORMAT = 'NATIONAL'`

It turns out that when you've set the `PHONENUMBER_DB_FORMAT` to `NATIONAL` it persists the number in that format.

If I remove this setting declaration, the phone number gets persisted as international (with prefixed country code), and everything works as expected.

**Comment by simonschmidt** [comment]
> Is this a change in behavior that broke with the most recent release? Was was the behavior you experienced before version 2.3.0?

I just started using the library, but I tried with 2.2.0 which correctly saves the data:

```
x = models.Example.objects.create(phone_number='+1234567')
x.phone_number
# Out: PhoneNumber(country_code=1, ...)

x.refresh_from_db()                                                                                                                         
x.phone_number                                                                                                                             
# Out: PhoneNumber(country_code=1, ....)
```

**Comment by overfl0** [comment]
> Might be related to #273.

Yes, it's the cause of the issue.
`def get_prep_value(self, value):`

now does a:
`if value.is_valid():`

and if it's not (which is the case), the saved value is set to:
`value = self.get_default()`

which happens to be an empty string when:
`phone_number = PhoneNumberField()`

I would expect an exception (like ValueError) to be raised instead of simply silencing that error by storing a random (from my point of view) value instead.

As a workaround, you can add a check in your save method:
```
    def save(self, *args, **kwargs):
        if self.phone_number and not self.phone_number.is_valid():
            raise PhoneNumberValueError('The phone number is invalid.')
        super().save(*args, **kwargs)
```

**Comment by jdufresne** [comment]
> I would expect an exception (like ValueError) to be raised instead of simply silencing that error by storing a random (from my point of view) value instead.

This makes a lot of sense to me. A PR implementing this with tests would be happily reviewed for merge.
