### ISSUE TITLE
When access phonenumberfield of instance, raise KeyError

### ISSUE THREAD

**Issue by msw123123** [stefanfoulis/django-phonenumber-field#291]
I have tried to access field of User instance. But specific model field raised KeyError. Other models is OK.
I found the issue #187 that used django version 1.10.
But, my django version is 1.11.7 and django-phonenumber-field is 2.3.1

User model like

<

    class User(AbstractBaseUser):
    email = models.EmailField(max_length=255,unique=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    name = models.CharField(max_length=100, blank=True, null=True)
    lang = models.CharField(max_length=20, blank=True, null=True)
    country = models.CharField(max_length=20, blank=True, null=True)
    profile_image = models.URLField(max_length=500, blank=True, null=True)
    birth = models.DateField(null=True)
    phone = PhoneNumberField(null=True)
    abc = PhoneNumberField(null=True)

    kakao_id = models.CharField(max_length=64, blank=True, null=True)
    facebook_id = models.CharField(max_length=32, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
>

When I access user.phone, raise like
<

    Traceback (most recent call last):
    File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/code.py", line 91, in runcode
      exec(code, self.locals)
    File "<console>", line 1, in <module>
    File "/Users/moon/Documents/.venvs/timespread/lib/python3.5/site- 
    packages/phonenumber_field/modelfields.py", line 37, in __get__
      return instance.__dict__[self.field.name] 
    KeyError: 'phone'
>
What is wrong?

**Comment by jdufresne** [comment]
Looks very similar to a Django fix: https://github.com/django/django/commit/7c33aa8a87d323f0e8e5368705aa8ba96f9819d0
