### ISSUE TITLE
Bug or unexpected behaviour: sql transforms to IS NULL

### ISSUE THREAD

**Issue by un1t** [stefanfoulis/django-phonenumber-field#292]
I've updated package from 2.1.0 to 2.3.1. In 2.1.0 this worked as expected.

When we provide invalid phone number to query

    User.objects.filter(phone='123').query.__str__()

if transforms to such sql:

    SELECT *  users where phone IS NULL

Not existing number should return empty result, but we receive all user with not set phone number. It is totally unexpected. 

If phone is used for authentication, probably it could lead to security vulnerabilities.

**Comment by jdufresne** [comment]
Thanks for the report. I have confirmed the bug and am looking into a fix.
