### ISSUE TITLE
Form error

### ISSUE THREAD

**Issue by alokRamteke** [stefanfoulis/django-phonenumber-field#305]
I am entering the following number in PhoneNumberField:
9684611186
It is a valid phone number, but I am still getting an error `Enter a valid phone number.`

I am using `PhoneNumberInternationalFallbackWidget` widget in my code.

`PHONENUMBER_DB_FORMAT = 'NATIONAL'`
`PHONENUMBER_DEFAULT_REGION = 'MM'`

As I checked in the package, I am getting False in [`is_valid_number_for_region`](https://kite.com/python/docs/phonenumbers.phonenumberutil.is_valid_number_for_region
)
function.

What is wrong with the number or am I using the wrong widget?
I didn't find any documentation to it.

**Comment by amateja** [comment]
Hi @alokRamteke

This package is just a wrapper around [python-phonenumbers](https://github.com/daviddrysdale/python-phonenumbers) with tones of goodies. When you have some issue with your phone number usually it means that [python-phonenumbers](https://github.com/daviddrysdale/python-phonenumbers) is not able to parse it.

I think you were running a bit old version of [python-phonenumbers](https://github.com/daviddrysdale/python-phonenumbers). Please update your dependencies and you should be just fine as I'm able to parse your example phone number successfully.

```pycon
>>> import phonenumbers
>>> 
>>> region = 'MM'
>>> number_str = '9684611186'
>>> number = phonenumbers.parse(number=number_str, region=region)
>>> phonenumbers.is_valid_number(number)
True
>>> phonenumbers.is_valid_number_for_region(number, region_code=region)
True
```

```bash
$ pip list
Package                  Version
------------------------ -------
asgiref                  3.5.0
Django                   4.0.2
django-phonenumber-field 6.1.0
phonenumbers             8.12.43
pip                      22.0.3
setuptools               60.9.3
sqlparse                 0.4.2
wheel                    0.37.1
```
