### ISSUE TITLE
Locale HY

### ISSUE THREAD

**Issue by melikyan-a** [stefanfoulis/django-phonenumber-field#315]
Can you add the new locale 'HY' (Armenian)?
I can translate.

**Comment by jdufresne** [comment]
We sure can. Would you like to open a PR?

**Comment by melikyan-a** [comment]
Yes, if you don't mind.

**Comment by jdufresne** [comment]
That would be great! Thanks.

**Comment by melikyan-a** [comment]
Added,  #316

**Comment by thedrow** [comment]
Thank you!
