### ISSUE TITLE
Question: POST params when using PhoneNumberPrefixWidget

### ISSUE THREAD

**Issue by osroca** [stefanfoulis/django-phonenumber-field#320]
Thanks for your work on this Django plugin.

I'm using it in a project and I have a question regarding how the use of PhoneNumberPrefixWidget behaves in a ModelForm.

I have a ModelForm when I define my phonenumber field like this:

```python
class MyModelForm(forms.ModelForm):
    class Meta:
        model = MyModel

    ...
    phone = PhoneNumberField(
        label=_('Phone'),
        required=True,
        widget=PhoneNumberPrefixWidget(
            attrs={
                'class': 'form-control'
            }
        ),
        strip=True
    )
```

I render the form manually:

```python
<div class="form-group col-12 col-md-6">
    <label for="{{form.phone.auto_id}}">{{form.phone.label}}</label>
    {{ form.phone }}
    {{ form.phone.errors|safe }}
</div>
```

This ends rendering in the HTML two inputs, a `select` with the name `phone_0` for the prefix selector and an `input` with name `phone_1` for the actual phone number.

The problem is that the form doesn't validate because in the POST we don't have any `phone` parameter and since the field is required.

**The question is**:
Do I need to handle this on my own and convert `phone_0` and `phone_1` into a PhoneNumber instance?

**Comment by francoisfreitag** [comment]
I think you will need to render both widgets manually. Looking at what Django is doing for multiwidgets is probably helpful.
https://github.com/django/django/blob/stable/4.1.x/django/forms/templates/django/forms/widgets/multiwidget.html
