### ISSUE TITLE
Algerian Phone Number is not accepted, throwing invalid

### ISSUE THREAD

**Issue by Simouche** [stefanfoulis/django-phonenumber-field#329]
When i enter my phone number "+213799136332" or any other valid algerian phone number, it doesn't accept it, throwing :

> Enter a valid phone number (e.g. +12125552368).

i tried changing to diffrent `PHONENUMBER_DB_FORMAT` none of them worked, i tried with default region as `DZ` and entered a number with and without country code it throws:

> Enter a valid phone number (e.g. 012 34 56 78) or a number with an international call prefix.

so please, any help is appreciated.

**Comment by stefanfoulis** [comment]
`django-phonenumber-field` delegates the actual number parsing to https://github.com/daviddrysdale/python-phonenumbers . Could you try to parse your phone number directly with that lower level library?
That would help to narrow down if this is a `django-phonenumber-field` specific error or actually a problem in `python-phonenumbers`.

**Comment by samitnuk** [comment]
@Simouche @stefanfoulis 

I added PR #342 to show that the provided phone number is valid for both form and model. Please correct me if I missed something.

**Comment by stefanfoulis** [comment]
@Simouche are you still experiencing this issue?
