### ISSUE TITLE
ValueError when use PhoneNumberField as USERNAME_FIELD

### ISSUE THREAD

**Issue by AmirMahmood** [stefanfoulis/django-phonenumber-field#333]
I have changed USERNAME_FIELD  to a PhoneNumberField field to use this field as username in admin login page.
but when i enter an invalid phone number, it throw ValueError instead of showing form error message.

> ValueError at /fa/admin/login/
> “1234” is not a valid phone number.

**Comment by jdufresne** [comment]
Looks like a duplicate of #334.
