### ISSUE TITLE
AttributeError: module 'django.db.models' has no attribute 'PhoneNumberField'

### ISSUE THREAD

**Issue by BrucknerdeV** [stefanfoulis/django-phonenumber-field#340]
Django 2.2.5 in virtual environment.  I did the pip installs, updated the INSTALLED APPS & imported the PhoneNumberField.  models.py throws above error on python manage.py.migrate in new Model - Contacts.  Relevant code below - Much obliged, Bruckner.

`from django.db import models
from django.contrib.auth.models import User
from phonenumber_field.modelfields import PhoneNumberField

# Create your models here.

class Currencie(models.Model):
    currency_Code = models.CharField(max_length=3, default="ZAR")
    currency_Description = models.CharField(max_length=30, default=" ")

    class Meta:
                #Gives the proper plural name for admin
                verbose_name_plural = "Currencies"

    def __str__(self):
        return self.currency_Code

class Organisation(models.Model):
    org_Name = models.CharField(max_length=100,unique=True)
    org_Site = models.URLField(unique=True, default="http://angloamerican.co.za", verbose_name="Org Web Site")
    org_HQ_Location = models.CharField(max_length=30, default="Cape Town")
    org_Sector = models.CharField(max_length=70, default="Investment Instruments - Equity Investment Instruments")
    currency_Code = models.ForeignKey(Currencie, related_name="cc", on_delete=models.CASCADE)
    org_Turnover = models.IntegerField(default=0)
    org_Parent = models.CharField(max_length=100, default="Check")
    org_Multi_National = models.CharField(max_length=1, default="Y/N", verbose_name="Multi-National?")
    org_Comments = models.TextField(default="Enter relevant info here:")

    def __str__(self):
        return self.org_Name

class Contacts(models.Model):
    con_First_Name = models.CharField(max_length=64)
    con_Last_Name = models.CharField(max_length=64)
    con_Address = models.EmailField(unique=True)
    con_Land_Line = models.PhoneNumberField(region="ZA")
    con_mobile = models.PhoneNumberField(region="ZA")
    con_Org = models.ForeignKey(Organisation, on_delete=models.CASCADE)

class Exec(models.Model):
    exec = models.OneToOneField(User, on_delete=models.CASCADE)

    #exec_First_Name = models.CharField(max_length=30, default="First Name")
    #exec_Last_Name = models.CharField(max_length=30, default="Last Name")
    #exec_Mail = models.EmailField(default="someone@mail.com")
    exec_Title = models.CharField(max_length=30, default="Position")
    exec_Location = models.CharField(max_length=30, default="Cape Town")
    currency_Code = models.ForeignKey(Currencie, on_delete=models.CASCADE)
    exec_Target = models.IntegerField(default=0)
    exec_Comments = models.TextField(default="Comments")

    # Additional
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        #fullname = str(self.exec_First_Name) +" " + str(self.exec_Last_Name)
        #return fullname
        return self.exec.username

**Comment by jdufresne** [comment]
`con_Land_Line = models.PhoneNumberField(region="ZA")`

This line is incorrect. The `PhoneNumberField` is not a part of Django's `models` module. You need to import it from `phonenumber_field`.

**Comment by BrucknerdeV** [comment]
I think I have  a syntax understanding issue.  If I read your response correctly, the models.py should include:
from phonenumber_field.modelfields import PhoneNumberField
And the class should contain:
con_Land_Line = models.phonenumber_field.PhoneNumberField(region="ZA")

This doesn’t work – I get the following error when I migrate:
File "/Volumes/Data/DevelopmentTraining/PBS_v1.0/PBS/pbs1/models.py", line 38, in Contacts
    con_Land_Line = models.phonenumber_field.PhoneNumberField(region="ZA")
AttributeError: module 'django.db.models' has no attribute 'phonenumber_field'

Much obliged.

Bruckner de Villiers
+2783 625 1086

**Comment by jdufresne** [comment]
The import looks good. Try changing
```py
con_Land_Line = models.phonenumber_field.PhoneNumberField(region="ZA")
```
To:

```py
con_Land_Line = PhoneNumberField(region="ZA")
```

**Comment by BrucknerdeV** [comment]
Jon,
Thank you for the quick response.  It worked.  The issue was caused by me accepting the VSCode auto-complete value.
Regards,

Bruckner de Villiers
083 625 1086
