### ISSUE TITLE
Remove raising ValueError from save()

### ISSUE THREAD

**Issue by karolyi** [stefanfoulis/django-phonenumber-field#344]
Guys, this is getting ridiculous.

As argued in #337, raising errors on save() is a HUGE problem. The pull request is there, I try to get some action on it, yet I get ignored each time.

Please merge that pull request, because I'm just getting seemingly unsolvable errors (without a huge hack workaround, going to the SQL level) in my business application that has lots of old data.

The arguments as to why raising an error on save is a mistake, are all there in the pull request. Please don't go ignoring it.

**Comment by stefanfoulis** [comment]
I am sorry for the problems this is causing for you. I've simply not had the time to review and test myself. I'll try to find the time to do this weekend.

**Comment by bartmika** [comment]
+1

**Comment by stefanfoulis** [comment]
this has been solved in release `4.0.0`
