### ISSUE TITLE
Install phonenumbers dependency automatically?

### ISSUE THREAD

**Issue by matthijskooijman** [stefanfoulis/django-phonenumber-field#350]
The instruction currently say to explicitly `pip install phonenumbers`, but could this not just be declared as a dependency in setup.py so pip will automatically install it when installing `django-phonenumber-field`?

**Comment by matthijskooijman** [comment]
Ah, I see that there is alos the option of using `phonenumberslite`, that would explain why it is not missing (also seeing #230). However, I think you can add optional dependencies (e.g. you could `pip install django-phonenumber-field[lite]`), but I'm not entirely sure if you can *remove* a dependency when such an extra flag is specified...

**Comment by jdufresne** [comment]
These extras already exist:

https://github.com/stefanfoulis/django-phonenumber-field/blob/master/setup.py#L14-L17

**Comment by matthijskooijman** [comment]
Ah, overlooked those. Maybe the instructions should make those explicit? e.g.:

>     pip install django-phonenumber-field[phonenumbers]
>
> The `[phonenumbers]` extra specifier indicates to use the `phonenumbers` package. Alternatively, the `phonenumberslite` package can be used which has [a lower memory footprint](https://github.com/daviddrysdale/python-phonenumbers#memory-usage):
>
>     pip install django-phonenumber-field[phonenumberslite]

**Comment by jdufresne** [comment]
I like that suggestion. Thanks!
