### ISSUE TITLE
Return the phone number as "+012345678901"

### ISSUE THREAD

**Issue by kamalmeh** [stefanfoulis/django-phonenumber-field#361]
Hi There
I have used this module in my project and extended default django User Model to CustomUser with AbstractUser class. I added "mobile" field in that with PhoneNumberField. 
My use case:
1. I called an API and get the active user
2. I extracted the mobile PhoneNumberField as object.
3. I want to get the number from the object and send sms to it.

I have tried to find out how to get the number but could not find anything which help me.
My question is : how can I get the mobile number in string format from the object?

Thanks!

**Comment by folt** [comment]
It all depends on the format in which you want to receive the phone.

**Comment by amateja** [comment]
As @folt wrote it depends what is required. By default you get some shortcuts from this project like:

```pycon
>>> from phonenumber_field.modelfields import PhoneNumber
>>> 
>>> number = PhoneNumber.from_string('+33612345678', 'FR')
>>> number.as_international
'+33 6 12 34 56 78'
>>> number.as_national
'06 12 34 56 78'
>>> number.as_e164
'+33612345678'
>>> number.as_rfc3966
'tel:+33-6-12-34-56-78'
```
If this is not enough then you may fall back to [python-phonenumbers](https://github.com/daviddrysdale/python-phonenumbers) features but this is outside of the scope of this project I'm afraid.
