### ISSUE TITLE
graphql phone number serialize error

### ISSUE THREAD

**Issue by kamranhossain** [stefanfoulis/django-phonenumber-field#366]
In django-phonenumber-field when I use graphql(django-graphene, django-graphql-jwt) for authToken mutation. It gives me this error,

 _**"message": "Object of type PhoneNumber is not JSON serializable".**_ 

Is there any way to work it with graphql or I need to go through the custom drf serializar for this issue.  Thanks.

**Comment by kamranhossain** [comment]
I make the CharField rather than Phonenumberfield. It's work now.

**Comment by brahimchougrani** [comment]
> I make the CharField rather than Phonenumberfield. It's work now.

hey, @kamranhossain I'm having the same problem where did you change the field?

**Comment by kamranhossain** [comment]
I make CharField to phone number in model and add phone number validator.
import the validator from phonenumber_field.validators.

```
from phonenumber_field.validators import validate_international_phonenumber
phone_number = models.CharField(
        max_length=15, validators=[validate_international_phonenumber], unique=True
    ) 

```
