### ISSUE TITLE
"Enter a valid phone number" in admin

### ISSUE THREAD

**Issue by simondrabble** [stefanfoulis/django-phonenumber-field#369]
Django 3.0.5

From django admin, with a configured phone number field, and with 

`PHONENUMBER_DB_FORMAT = 'E164'`

if I enter a phone number without a leading country code (e.g. +1), I get:

`Enter a valid phone number (e.g. +12125552368)`

I can't enforce my admins to always remember to add the +1. Is there a way to set a default country code? in the US, (212) 555-2368 IS a valid phone number.

**Comment by Benbb96** [comment]
Does adding `PHONENUMBER_DEFAULT_REGION = 'US'` in your settings makes it work ?

**Comment by simondrabble** [comment]
Yes it does - I discovered that, should have closed the issue. Thanks for the response!
