### ISSUE TITLE
How do you check if the phonenumber is valid before saving?

### ISSUE THREAD

**Issue by sowinski** [stefanfoulis/django-phonenumber-field#372]
Hi,

how do you check if the phonenumber is valid before saving?
```
class Test(models.Model):
    mobile = models.CharField(max_length=30,null=True, blank=True)
    formated_mobile = PhoneNumberField(blank=True)
```

Let's assume mobile is populated with something obvious wrong. (For example mobile="test")

If I do something like that.
t = Test.objects.all().first()
t.formated_mobile = t.mobile #Where t.mobile == "test"
t.save()

I can save the wrong number without an error.

1) Is this a bug or feature?
2) How can I check if t.mobile is correct or not?

Thank you

**Comment by francoisfreitag** [comment]
The model is not a good place to perform validation with Django. They are intended to deal with validated data. I believe you are looking for a Form (https://docs.djangoproject.com/en/3.1/topics/forms/). The job of forms is to validate user inputs.

This library provides a form field for phone numbers, the `phonenumber_field.formfields.PhoneNumberField`. You should feed the data submitted by your users to a Form that contains a PhoneNumberField and let it validate the data.

**Comment by ahsetiaki** [comment]
> The model is not a good place to perform validation with Django. They are intended to deal with validated data.

dear @francoisfreitag, can you elaborate more about this statement? I'm using DRF and I knew I can handle it on serializer level, very similar as handling it on ModelForm. But I need to ensure the data integrity on the lowest level possible. My plan is to create object validation on the model level then DRF will handle it by catching Django ValidationError. 

I'm struggle to find any sources that support my plan and I always find many sources that seems support your statement like this [SO thread](https://stackoverflow.com/questions/13036315/correct-way-to-validate-django-model-objects). Can you enlighten me? Thanks in advance!
