### ISSUE TITLE
Support Arabic Translation

### ISSUE THREAD

**Issue by ahmedsafadii** [stefanfoulis/django-phonenumber-field#374]
Is it possible to support Arabic translations?

**Comment by francoisfreitag** [comment]
Yes, you can contribute translations by creating a translation file. Can follow this guide https://docs.djangoproject.com/en/dev/topics/i18n/translation/#localization-how-to-create-language-files.

Once you’ve created the translation files (and compiled them), please create a pull request https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request with your changes.

Someone will review them, work with you to make sure it meets the repository standards, and integrate them.
