### ISSUE TITLE
Using django-phonenumber-field in Heroku

### ISSUE THREAD

**Issue by vivek0079** [stefanfoulis/django-phonenumber-field#375]
Hello, 

I was trying to deploy a Django project (django-phonenumber-field installed) in Heroku. The requirements.txt file contained the following 
`
asgiref==3.2.10
Babel==2.8.0
dj-database-url==0.5.0
Django==3.0.8
django-phonenumber-field==4.0.0
gunicorn==20.0.4
phonenumbers==8.12.7
psycopg2-binary==2.8.5
pytz==2020.1
sqlparse==0.3.1
`
The build is deployed successfully in Heroku. But Heroku was not able to identify the `'phonenumber_field',` in the `settings.py`, and fails to run the build. 

Does this issue raise due to the name mismatch between the requirements and installed_apps?

How can this be fixed?

**Comment by cloudmex-alan** [comment]
Same question running on a AWS Ligtsail bitnami django instance.

**Comment by arnaudlimbourg** [comment]
@vivek0079 the recent release of 5.0.0 should solve this as it adds support for this django version if I'm not mistaken

**Comment by francoisfreitag** [comment]
Looks like the original issue is solved? Please close the issue if that’s the case.
