### ISSUE TITLE
Custom error messages not working

### ISSUE THREAD

**Issue by 24thDawn** [stefanfoulis/django-phonenumber-field#387]
The default error message
`Enter a valid phone number (e.g. +12125552368).`
overwrites any custom error messages passed via form.py.
 
```
form.py
.......

phonenumber = PhoneNumberField(required=True, error_messages={'required':' Enter a number like this +2341111111111'})

......
```

The above gets overridden by the misleading default error message. Is there a way around this?

**Comment by ValerianThomas** [comment]
You can override the class and adapt your own default message:
`class CustomPhoneNumberField(PhoneNumberField):
    default_error_messages = {"invalid": _("Custom Message")}`

**Comment by 24thDawn** [comment]
Thanks, it worked! The only addition is to import "_" like below

```
from django.utils.translation import gettext as _
class CustomPhoneNumberField(PhoneNumberField):
    default_error_messages = {"invalid": _("My_Custom_Message")}
```
