### ISSUE TITLE
adding ability to use a callable for PHONENUMBER_DEFAULT_REGION setting

### ISSUE THREAD

**Issue by stygmate** [stefanfoulis/django-phonenumber-field#398]
Hi,

My case is a SaaS where different customers need a different PHONENUMBER_DEFAULT_REGION for having "natural" input (without having to add prefix if inside the region) for phone numbers fields.

I though that adding the possibility to enter a function as a string (ex: ```"tools.phoneregion.dynamic_default_region"``` if string present in regions list we use region if not we try to import function) can resolve my case.

Maybe we have to add a internal settings.py to the app to evaluate only once PHONENUMBER_DEFAULT_REGION and modify some reference to settings in the code.

**Comment by francoisfreitag** [comment]
Why not initialize the form based on your customer’s region? Something like:

```python
class ProfileForm(Form):
    def __init__(self, *args, *, user **kwargs):
        super().__init__(*args, **kwargs)
        region = dynamic_region_for(user)
        self.fields["phone_number"] = phonenumber_field.formfields.PhoneNumberField(region=region)
```

**Comment by francoisfreitag** [comment]
Assuming the issue has been resolved.
