### ISSUE TITLE
Versioning scheme

### ISSUE THREAD

**Issue by videda** [stefanfoulis/django-phonenumber-field#411]
A question on versioning of `django-phonenumber-field`. I could not find a
document describing this. Sorry if I missed it.

Do you follow some specific versioning scheme? Possibly semantic versioning?

Will it always be safe to upgrade `A.B.N -> A.B.(N+1)`?

Thanks!

**Comment by francoisfreitag** [comment]
Yes, we try to follow semantic versioning. Basically, breaking changes would bump the major, releases that are backward compatible are released as minor and nasty bugs are fixed with a patch release.
