### ISSUE TITLE
Admin page won't save with unique=True, null=True

### ISSUE THREAD

**Issue by apollograce** [stefanfoulis/django-phonenumber-field#432]
We have a model with a phone number that needs to be unique, but which can be null or blank:
`    phoneNumber = PhoneNumberField(blank=True, null=True, unique=True)`

The blank doesn't really help us here, because unique means that only one phone number can be the empty string. But null should be good - and generally works fine.

The problem comes when we edit an instance of this model in the Django admin. It fails because the form takes a phone number of null, but saves it from the text field as the empty string. So the non-unique criterion is violated.

What's the way forward on this? I imagine this is a common use case - wanting unique phone numbers, wanting to be able to edit them in admin, but also allowing null?

**Comment by francoisfreitag** [comment]
Hi,

Thanks for reporting. I tried using `PhoneNumberField(blank=True, null=True, unique=True)` in a project and the admin saves `NULL` in my postgresql database.

Could you try creating a test case or minimal project that reproduces the issue?

The following test passes the test suite on the `main` branch:

```diff
diff --git a/tests/test_formfields.py b/tests/test_formfields.py
index d207ed3..9aad1f8 100644
--- a/tests/test_formfields.py
+++ b/tests/test_formfields.py
@@ -3,6 +3,8 @@ from django.test import SimpleTestCase
 
 from phonenumber_field.formfields import PhoneNumberField
 
+from .models import NullablePhoneNumber
+
 ALGERIAN_PHONE_NUMBER = "+213799136332"
 
 
@@ -45,3 +47,8 @@ class PhoneNumberFormFieldTest(SimpleTestCase):
         form = PhoneNumberForm({"number": ALGERIAN_PHONE_NUMBER})
         self.assertTrue(form.is_valid())
         self.assertEqual(ALGERIAN_PHONE_NUMBER, form.cleaned_data["number"])
+
+    def test_nullable_form_field(self):
+        fields = forms.fields_for_model(NullablePhoneNumber, ["phone_number"])
+        field = fields["phone_number"]
+        self.assertIsNone(field.clean(""))
```

**Comment by apollograce** [comment]
Thank you for the affirmation that this should be working. I've realized I'm working with an old release of django-phonenumberfield (1.3.0). I'm going to see if I can get a more current version. If I can still reproduce the issue, I'll post a minimal project here.
