### ISSUE TITLE
KZ locale instead of RU

### ISSUE THREAD

**Issue by repair-cat** [stefanfoulis/django-phonenumber-field#438]
when i select the Russian localization ( PHONENUMBER_DEFAULT_REGION = 'RU' in settings.py), Kazakhstan is displayed in the template

**Comment by francoisfreitag** [comment]
Hi,

Can you precise what you see and provide a minimal test case or an example project?
Perhaps double-check the [internationalization configuration](https://docs.djangoproject.com/en/3.2/topics/i18n/translation/#how-django-discovers-language-preference)?

**Comment by repair-cat** [comment]
![models](https://user-images.githubusercontent.com/35627286/115579642-cb785600-a2df-11eb-8e66-876ab133e4d1.jpg)
![forms](https://user-images.githubusercontent.com/35627286/115579653-cf0bdd00-a2df-11eb-9e52-83cb7aebf764.jpg)
![kz](https://user-images.githubusercontent.com/35627286/115579659-d16e3700-a2df-11eb-8c67-e79389eec037.jpg)
![settings](https://user-images.githubusercontent.com/35627286/115579662-d16e3700-a2df-11eb-8b87-116763961cab.jpg)

**Comment by repair-cat** [comment]
if I change the country, then it works correctly. but RU does'n work

**Comment by francoisfreitag** [comment]
Good find, it looks like a bug! The following is ordering the prefix by label (Kazakhstan must be before Russia in your alphabet as well).
https://github.com/stefanfoulis/django-phonenumber-field/blob/e40d101c3514a3b6adcaf8185bc266fc11b0f9eb/phonenumber_field/widgets.py#L36-L44

The value is `+7` for both languages. The initial value is set to `+7` and the selected option is the first in alphabetical order with value `+7`.

**Comment by repair-cat** [comment]
I thought so, that it's all about the prefix. tell me, can I leave only the prefix without the country name? Some parameter?

**Comment by francoisfreitag** [comment]
We would welcome a contribution to fix the original issue.

It think the values should be a mix of region codes and prefixes. Something like `f"{prefix}-{region_code}`. All options would then have a different value, allowing to select the intended option as the initial value.

**Comment by sm-timmy** [comment]
Hope it help

    
       for prefix, values in _COUNTRY_CODE_TO_REGION_CODE.items():
                    prefix = "+%d" % prefix
                    if initial and initial in values:
                        self.initial = prefix
                    for country_code in values:
                        if country_code == 'KZ':
                            continue
                        country_name = locale.territories.get(country_code)
                        if country_name:
                            choices.append((prefix, "{} {}".format(country_name, prefix)))

**Comment by francoisfreitag** [comment]
The suggested solution is single casing the `KZ` locale. This is not a good solution, as users may want to select `KZ`.

**Comment by francoisfreitag** [comment]
I believe this has been fixed with #493.
