### ISSUE TITLE
Problem to validate short business numbers

### ISSUE THREAD

**Issue by Ali-Javanmardi** [stefanfoulis/django-phonenumber-field#441]
Hi,

I just tried django-phonenumber-field in my project and it seems so good.
but I have problem to enter short numbers specially 4 or 5 digit numbers that used to use for business call centers.

Is there any settings that let me validate such numbers or it need a hack?

**Comment by francoisfreitag** [comment]
This field is only wrapping Google’s https://github.com/google/libphonenumber.
If that library allows validating such numbers, then this project will. If not, this project won’t.

**Comment by KIRA009** [comment]
@Ali-Javanmardi Not sure if this is still helpful, but we recently faced the same issue, and the solution we figured was to override the validators and the `to_python` method

```python
from django.core import validators
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from phonenumber_field.formfields import PhoneNumberField as PhoneNumberFormField
from phonenumber_field.modelfields import PhoneNumberField
from phonenumber_field.phonenumber import PhoneNumber, to_python
from phonenumbers import is_valid_short_number


def validate_international_phonenumber(value):
    phone_number = to_python(value)
    if isinstance(phone_number, PhoneNumber) and not (
        phone_number.is_valid() or is_valid_short_number(phone_number)
    ):
        raise ValidationError(
            _("The phone number entered is not valid."), code="invalid_phone_number"
        )


class CustomPhoneNumberFormField(PhoneNumberFormField):
    default_validators = [validate_international_phonenumber]

    def to_python(self, value):
        phone_number = to_python(value, region=self.region)

        if phone_number in validators.EMPTY_VALUES:
            return self.empty_value

        if phone_number and not (
            phone_number.is_valid() or is_valid_short_number(phone_number)
        ):
            raise ValidationError(self.error_messages["invalid"])

        return phone_number


class CustomPhoneNumberField(PhoneNumberField):
    validators = [validate_international_phonenumber]

    def formfield(self, **kwargs):
        overrides = {
            "form_class": CustomPhoneNumberFormField,
        }
        kwargs.update(overrides)
        return super().formfield(**kwargs)
```

**Comment by Ali-Javanmardi** [comment]
Dear @KIRA009 

Thanks for your reply,
This question was for a long time ago and I ignored using any special field for phone-number in my project.

I hope your hack is working and will help anyone who has same problem. 
I will test your suggested code as soon as I create a test project to use this field type again.

Thanks again

**Comment by francoisfreitag** [comment]
I have closed this issue too quickly, sorry about that. Exposing an option to control accepting short numbers in the field (defaulting to `False` for BC), that updates the `is_valid()` logic to accept valid short numbers (`is_valid_short_number`) would make sense.
