### ISSUE TITLE
"phonenumber_field.modelfields" could not be resolved

### ISSUE THREAD

**Issue by madatbay** [stefanfoulis/django-phonenumber-field#450]
Hi, I'm trying to follow dcs to install and use `django-phonenumber-field`. Though I have installed library like this:
`pip install django-phonenumber-field[phonenumbers]` and `pip install django-phonenumber-field[phonenumberslite]` I still get error "phonenumber_field.modelfields" could not be resolved when I try to import to my `models.py`

**Comment by francoisfreitag** [comment]
I cannot reproduce the issue in a fresh environment.

Can you share the steps you’ve followed precisely, or a minimal failing project? Are you using a virtualenv? If so, is it activated?

**Comment by madatbay** [comment]
Yes I'm using venv and it's activated. I solved the issue with the venv. It seems like, though venv is activated, somehow, vscode was trying to use original `Python` environment, changed it to venv and problemd solved. Closing issue
