### ISSUE TITLE
values_list() returns the non international format

### ISSUE THREAD

**Issue by Tobeyforce** [stefanfoulis/django-phonenumber-field#452]
When trying to add a phone_number field to list using the values_list() it will return the phone_number field as a string in its non-international form even though I've added my settings:

PHONENUMBER_DB_FORMAT = 'NATIONAL'
PHONENUMBER_DEFAULT_REGION = 'SE'

e.g 070 255 25 25 instead of +46 70 255 25 25, is this intentional?
This is my DB query.
users = CustomUser.objects.annotate(subscribed_city_list=ArrayAgg('subscribed_city__name')).values_list('subscribed_city_list', 'user_id', 'phone_number').order_by('user_id')

This is what the data coming out looks like:
<QuerySet [('test@hotmail.com',  ['vienna', 'stockholm'], UUID('0c9d04de-b28f-410f-8963-be24edd74070'), '070-255 25 25')]>

Would be nice to have an explanation as to why, and what I might be able to do instead. I unfortunately can't change the query up for various reasons.

**Comment by Tobeyforce** [comment]
Ok so changing
PHONENUMBER_DB_FORMAT = 'NATIONAL'
PHONENUMBER_DEFAULT_REGION = 'SE'
to just
PHONENUMBER_DB_FORMAT = 'INTERNATIONAL'
seems to have done it.. however, now I lose some of the functionality I previously had which would always make sure it ended up a national number of my choice (SE). What am I doing wrong?

**Comment by Tobeyforce** [comment]
Sorry, setting it to 'INTERNATIONAL' but keeping the phonenumber_default_region seemed to have done the trick. Perhaps I missunderstood your documentation.

**Comment by francoisfreitag** [comment]
https://github.com/stefanfoulis/django-phonenumber-field/pull/462 is an attempt to clarify existing settings and their purpose.
