### ISSUE TITLE
How do you limit the number of choices of the widget

### ISSUE THREAD

**Issue by superflyer11** [stefanfoulis/django-phonenumber-field#458]
Is there a built-in setting to limit the number of choices to specific ones? Or do I need to override the select widget?

**Comment by amateja** [comment]
Currently there is no other way than a hacky one. After instantiation of `PhoneNumberPrefixWidget` you might access `PhoneNumberPrefixWidget.widgets` property, get an instance of `PhonePrefixSelect` and alter `PhonePrefixSelect.choices` property.

On the other hand we might change both `PhoneNumberPrefixWidget` and `PhonePrefixSelect` constructor to accept `choices` argument... but I need to get some thumbs up on it.
