### ISSUE TITLE
form field clears when either country code or phone number text is empty

### ISSUE THREAD

**Issue by KunjPrasad** [stefanfoulis/django-phonenumber-field#461]
For an edge case where user would have entered phone number text but not select country code, or selected the country code but not added the phone number, I am noticing that when the form is submitted, then due to [`if all(values):`](https://github.com/stefanfoulis/django-phonenumber-field/blob/main/phonenumber_field/widgets.py#L74) check in `PhoneNumberPrefixWidget.value_from_datadict` method, the rerendered form has user entries wiped out.

I feel a better experience would be to leave the partial user data on form as-is. I am not sure if the criteria is even helping at all, and if it is better removed, i.e. simply `return "%s.%s" % tuple(values)` for all cases. Anyways, the `to_python` method in `formfields.PhoneNumberField` will raise a validation error ([here](https://github.com/stefanfoulis/django-phonenumber-field/blob/main/phonenumber_field/formfields.py#L46))

**Comment by amateja** [comment]
This should be addressed as a side effect of implementing #493 and is related to #489.
