### ISSUE TITLE
Object of type PhoneNumber is not JSON serializable when running manage.py dumpdata

### ISSUE THREAD

**Issue by scroogeT** [stefanfoulis/django-phonenumber-field#466]
I have a custom user model with a PhoneNumber field as below:

`
class CustomUser(AbstractBaseUser, PermissionsMixin):
   
   phone = PhoneNumberField(_('phone number'), unique=True)

    email = models.EmailField(_('email address'), max_length=254, unique=True, null=True, blank=True)

    full_name = models.CharField(_('full name'), max_length=254,
                                 help_text=_('The full name as it appears on ID or passport'))
`

When I want to export any model that is linked to my user model 

`python manage.py dumpdata --natural-foreign --natural-primary --indent 2 users.customuser users.userprofile > testUsers.json`

It's failing with this error:

> CommandError: Unable to serialize database: Object of type PhoneNumber is not JSON serializable

However when I run: 

`python manage.py dumpdata --natural-foreign --natural-primary --indent 2 users.customuser > testUsers.json`

It's working just fine. The problem comes for models linked to my user model

**Comment by francoisfreitag** [comment]
That makes sense, you should update the serializer (probably currently https://docs.djangoproject.com/en/3.2/topics/serialization/#djangojsonencoder) to represent phone numbers.
Maybe this project can offer a subclass that encodes phone numbers as E164. OTOH, any other project with for a custom datatype would also need its own serializers and I expect users would need to define their own serializers anyway.

**Comment by scroogeT** [comment]
So @francoisfreitag how can a user define their own phone number field serializer while performing

> python manage.py dumpdata

**Comment by francoisfreitag** [comment]
https://docs.djangoproject.com/en/3.2/topics/serialization/#serialization-formats-json contains an example of how to register your own serializer for a given format.
