### ISSUE TITLE
Canada country code problem

### ISSUE THREAD

**Issue by aliceni81** [stefanfoulis/django-phonenumber-field#468]
If we select Canada, it will default to United States.
![Capture](https://user-images.githubusercontent.com/81170508/135551238-ffeb373d-cda7-4eda-bd67-4d0ee37e7328.PNG)

**Comment by francoisfreitag** [comment]
Without seeing the code, both inputs have the same value (Canada and US both use the +1 prefix). That’s likely the source of your issue.

**Comment by aliceni81** [comment]
@francoisfreitag Yes, thanks. Its the problem of my js code.
