### ISSUE TITLE
Can't run Django commands after using the widget

### ISSUE THREAD

**Issue by rvanlaar** [stefanfoulis/django-phonenumber-field#48]
When the widget is in use in the admin, the babel Locale is imported. 
The Django default locale: translation.get_language() is en-us.

In the admin I have configured the following:

formfield_overrides = {
        PhoneNumberField: {'widget': PhoneNumberPrefixWidget(initial='NL'), }
    }

Since I want to use an initial value for the country the PhonePrefixSelect is run.
This raises an error since Babel doesn't know the en-us locale.

Hence management commands die with this error: 
UnknownLocaleError: unknown locale 'en-us'

**Comment by cyberjoac** [comment]
Hi Brad, could you please write here your __init__ method, I can't figure out how to work it out.

Thanks a lot.

**Comment by brad** [comment]
@cyberjoac Sure:
```
from django import forms
from phonenumber_field.widgets import PhoneNumberPrefixWidget

class MyForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(MyForm, self).__init__(*args, **kwargs)
        self.fields['phone_number'].widget = PhoneNumberPrefixWidget
```

**Comment by samane78** [comment]
Saw this error when LANGUAGE_CODE was set to 'en-us'. If it's set to say 'en', then the error disappears.

Fixed it by adding following to phonenumber_field/widgets.py

from django.utils.translation import to_locale

class PhonePrefixSelect(Select):
    def __init__(self, initial=None):
         ...
         locale = Locale(to_locale(translation.get_language()))
         ...

**Comment by thedrow** [comment]
Is there a pull request about this issue?

**Comment by amateja** [comment]
Thank you for reporting. Our project has evolved since that time and this issue will be closed. Please update and reopen if you feel it is still applicable.
