### ISSUE TITLE
Use default region's format in error message

### ISSUE THREAD

**Issue by Vayel** [stefanfoulis/django-phonenumber-field#481]
Hi!

When the region is not explicitly specified for a form field, a fake phone number is used in the error message:

```
Enter a valid phone number (e.g. +12125552368).
```

It would be nice to use the format of the region defined in the settings (if exists). To do so, just replace `if region:` by `if self.region:` here: https://github.com/stefanfoulis/django-phonenumber-field/blob/main/phonenumber_field/formfields.py#L24

Thanks!

**Comment by francoisfreitag** [comment]
That’s a good idea, thanks for the suggestion. Do you mind testing #481 in your project, see if it behaves as you would expect?
