### ISSUE TITLE
Error with international numbers in form field

### ISSUE THREAD

**Issue by javialon26** [stefanfoulis/django-phonenumber-field#491]
Form field doesn't detect an international number and always triggers the validation error. I have the following configurations:

```
PHONENUMBER_DEFAULT_FORMAT = "NATIONAL"
```

I'm using the PhoneNumberInternationalFallbackWidget in Django admin with this phone number +1 (305) 793-1211 or +13057931211, I think the field should detect the international number (E164) like the documentation says: `a form widget that uses national numbers unless an international number is entered`

**Comment by francoisfreitag** [comment]
Can you provide a failing test or minimal project demonstrating the issue?
