### ISSUE TITLE
It looks like Nigerian numbers aren't being recognised at the moment

### ISSUE THREAD

**Issue by hendryjwr** [stefanfoulis/django-phonenumber-field#492]
As the title suggests. I'm using `django-phonenumber-field==6.1.0` and `phonenumbers==8.12.43`. An example number is "+234 901 529 1710". I have tried running a little test using the `PhoneNumberField` and it throws an `invalid` error. I wasn't too sure about testing on the `phonenumbers` package, but I can see `234: ("NG",),` within the `phonenumbers/data/` directory. Is anyone able to confirm if this is an error on the `django-phonenumber-field` side of things? Thanks in advance :)

**Comment by amateja** [comment]
Hi @hendryjwr 

This package is just a wrapper around [python-phonenumbers](https://github.com/daviddrysdale/python-phonenumbers) with tones of goodies. When you have some issue with your phone number usually it means that [python-phonenumbers](https://github.com/daviddrysdale/python-phonenumbers) is not able to parse it. On the other hand I have no issues with crunching your phone number and I also run same version of `django-phonenumber-field` and `phonenumbers`.

```pycon
>>> import phonenumbers
>>> from phonenumber_field.modelfields import PhoneNumber
>>> 
>>> number = '+234 901 529 1710'
>>> phonenumbers.parse(number=number)
PhoneNumber(country_code=234, national_number=9015291710, extension=None, italian_leading_zero=None, number_of_leading_zeros=None, country_code_source=0, preferred_domestic_carrier_code=None)
>>> PhoneNumber.from_string(number, region='NG')
PhoneNumber(country_code=234, national_number=9015291710, extension=None, italian_leading_zero=None, number_of_leading_zeros=None, country_code_source=1, preferred_domestic_carrier_code=None)
```

```bash
$ pip list
Package                  Version
------------------------ -------
asgiref                  3.5.0
Django                   4.0.2
django-phonenumber-field 6.1.0
phonenumbers             8.12.43
pip                      22.0.3
setuptools               60.9.3
sqlparse                 0.4.2
wheel                    0.37.1
```

It is always better to narrow an issue down to minimal working / non-working use-cases. Please share your not working code snippet because I couldn't replicate your issue.

**Comment by hendryjwr** [comment]
Hi @amateja, thanks for looking into this so quickly! I've tried running your tests as well, and it passes for me. Please see my code below and excuse the way it looks 😅 Please note I am running into the issue when trying to validate the number during serialization, apologies for not making this clear above.
```
import phonenumbers
from phonenumber_field.serializerfields import PhoneNumberField
from phonenumber_field.modelfields import PhoneNumber

UK_number = '+44 7446 869561'
NG_number = '+234 901 529 1710'

phonenumbers.parse(number=NG_number)
phonenumbers.parse(number=UK_number)
PhoneNumber.from_string(NG_number, region='NG')
PhoneNumber.from_string(UK_number, region='UK')

PhoneNumberField.to_internal_value(PhoneNumberField(), UK_number)
PhoneNumberField.to_internal_value(PhoneNumberField(), NG_number)
```

We are using the following settings 

```
PHONENUMBER_DB_FORMAT = "INTERNATIONAL"
PHONENUMBER_DEFAULT_REGION = "GB"

```

This fails at the final statement.

**Comment by amateja** [comment]
I'm really sorry but I couldn't reproduce your issue.
```pycon
>>> import phonenumbers
>>> from django.test import override_settings
>>> 
>>> from phonenumber_field.serializerfields import PhoneNumberField
>>> 
>>> @override_settings(
...     PHONENUMBER_DB_FORMAT='INTERNATIONAL',
...     PHONENUMBER_DEFAULT_REGION='GB'
... )
... def test_number(number_str: str) -> bool:
...     number = PhoneNumberField.to_internal_value(PhoneNumberField(), number_str)
...     return phonenumbers.is_valid_number(number)
... 
>>> UK_number = '+44 7446 869561'
>>> NG_number = '+234 901 529 1710'
>>> 
>>> test_number(UK_number)
True
>>> test_number(NG_number)
True
```

**Comment by hendryjwr** [comment]
How odd, running your code the nigerian number still fails for me. I'll look into this further but I suppose it must be somewhere on our end. Thanks for taking the time though :) Happy to close this
