### ISSUE TITLE
ModuleNotFoundError 'django_crontabphonenumber_field'

### ISSUE THREAD

**Issue by Griffins-sys254** [stefanfoulis/django-phonenumber-field#499]
I have installed django-phonenumber-field and I'm getting 
No module named 'django_crontabphonenumber_field'

**Comment by amateja** [comment]
Hi,

Could you share code snippet and traceback of your issue? Please also verify import statements and `INSTALLED_APPS` setting. It looks like missing colon.

Regards,
Andrzej

**Comment by amateja** [comment]
Please change:

```python
INSTALLED_APPS = [
    ...
    'django_crontab'
    'phonenumber_field'
]
```
into:
```python
INSTALLED_APPS = [
    ...
    'django_crontab',  # please note colon here
    'phonenumber_field'
]

**Comment by Griffins-sys254** [comment]
Hello thanks alot that was helpful

**Comment by amateja** [comment]
Glad I could help. Happy coding!

**Comment by Griffins-sys254** [comment]
do you mind to share your personal  contact?
