### ISSUE TITLE
Invalid format

### ISSUE THREAD

**Issue by chrisspen** [stefanfoulis/django-phonenumber-field#508]
This is more of a question than a bug.

By default, the widget validates this number

    +12125552368

but throws a ValidationError for this number:

    +14564797123

Why is this? How would I update the configuration to get the widget to accept this number?

**Comment by francoisfreitag** [comment]
The widget defers to the phonenumbers library, which is a wrapper around https://github.com/google/libphonenumber.
```python
>>> import phonenumbers
>>> x = phonenumbers.parse("+14564797123")
>>> phonenumbers.is_valid_number(x)
False
```

https://github.com/google/libphonenumber/blob/master/FALSEHOODS.md is probably a nice read.

One has to troubleshoot to understand why the number is invalid, but something in its construct probably fails one of the rules defined in libphonenumber. Either libphonenumber is wrong about that number, or the number really does not exist and should not be considered valid input.
