### ISSUE TITLE
The numbers saved with spaces in database

### ISSUE THREAD

**Issue by DevHussein** [stefanfoulis/django-phonenumber-field#513]
Dears,
I need support, I like the library it is very useful, but it has one issue when I make the below settings, the numbers saved with spaces in database like "050 XXX XXXX":

# Mobile number format settings
PHONENUMBER_DEFAULT_FORMAT = "NATIONAL"
PHONENUMBER_DB_FORMAT = "NATIONAL"
PHONENUMBER_DEFAULT_REGION = "SA"

I tried with  mobile_number = PhoneNumberField(trim_whitespace=True) in the serializer but not working

Could you please help me in that?

**Comment by francoisfreitag** [comment]
`trim_whitespace` only [trims leading and trailing whitespaces](https://www.django-rest-framework.org/api-guide/fields/#charfield). I would recommend against storing phone numbers in the `NATIONAL` format, as it prevents storing international phone numbers, and varies greatly from one country to the next. Using a normalized storage format (E164 or INTERNATIONAL) should help.

**Comment by DevHussein** [comment]
Oh, you are right! forgot that!
I need to use the national only but without saving the numbers in database with in between spaces. 
Is there any solution?

**Comment by francoisfreitag** [comment]
The search terms can probably be adapted to lookup numbers in the international format.

If you really want to store data in the national format, you’ll have to extend the library in your project to remove the whitespace, probably implementing your own `get_prep_value()` on the model field. Again, I would advise against such change.

**Comment by DevHussein** [comment]
I suggest on you to add this as optional to trim in between spaces until then I will use the international format.

**Comment by francoisfreitag** [comment]
Thank you for suggestion, but I am opposed to making this change. Using the `NATIONAL` format for the storage in the database is very likely (always?) a mistake. I do not want to encourage people in that direction, instead they should use the `E164`, or `INTERNATIONAL` format to store the data in a standard form that is easier to manipulate.
People are welcome to extend the library in their projects to mangle the phone number they store, but this library won’t maintain a feature that doesn’t match a popular use case.
