### ISSUE TITLE
Extra documentation for the use of the widget

### ISSUE THREAD

**Issue by rvanlaar** [stefanfoulis/django-phonenumber-field#52]
Could you expand the readme? 
I had problems getting a form with the widget to work.

Something like this:

To use the widget in a form with an initial country:

```
class PhoneForm(forms.Form):
    telephone = PhoneNumberField(
        widget=PhoneNumberPrefixWidget(initial='NL'),
        required=False,
    )
```

And to pass initial data to the form use the following code, when we have a user with 
a telephone field:

```
        data = {'telephone_0': '+%d' % user.telephone.country_code,
                    'telephone_1': user.telephone.national_number}
        form = PhoneForm(data)
```

**Comment by cyberjoac** [comment]
+1, it would be great if you could integrate it in the README.
Thanks so much.

**Comment by amateja** [comment]
Thank you for reporting. Our project has evolved since that time and this issue will be closed. Please update and reopen if you feel it is still applicable.

**Comment by lakenen** [comment]
@amateja has this project evolved beyond the need for documentation? 😂

**Comment by amateja** [comment]
Ask any surgeon - they love exploratory surgery more that diagnosis 😄.

Good point. Probably I didn't pay too much attention. Sorry.
