### ISSUE TITLE
No module named babel

### ISSUE THREAD

**Issue by danielbraun** [stefanfoulis/django-phonenumber-field#53]
When importing from widgets, I'm getting this error.
It's not listed in setup.py as a dependency, maybe that's why.

**Comment by cyberjoac** [comment]
+1

**Comment by llann** [comment]
+1

**Comment by madisvain** [comment]
+1 please fix this issue

**Comment by FuadMunzerinHossain** [comment]
+1

**Comment by thedrow** [comment]
I'll release soon and #76 will be included inside the new release.
