### ISSUE TITLE
How to write code raise `ValidationError` when save() in model ?

### ISSUE THREAD

**Issue by kev26** [stefanfoulis/django-phonenumber-field#541]
I saw that `PhoneNumber` would use `validate_international_phonenumber` to check validation, but when I used django admin or shell to interact with data via ORM, the phone number was still saved. How to prevent this step and  raise `ValidationError` ? Thanks so much

**Comment by francoisfreitag** [comment]
You should call [`Model.full_clean`](https://docs.djangoproject.com/en/4.1/ref/models/instances/#django.db.models.Model.full_clean) in your admin/ORM.

A recent discussion on the django-developers Google Group shows this behavior won’t become the default, and the developers who want that validation are responsible for calling it.
https://groups.google.com/g/django-developers/c/RHTR8stBsr8

**Comment by kev26** [comment]
> You should call [`Model.full_clean`](https://docs.djangoproject.com/en/4.1/ref/models/instances/#django.db.models.Model.full_clean) in your admin/ORM.
> 
> A recent discussion on the django-developers Google Group shows this behavior won’t become the default, and the developers who want that validation are responsible for calling it. https://groups.google.com/g/django-developers/c/RHTR8stBsr8

thanks you !
