### ISSUE TITLE
Phone number validator not work

### ISSUE THREAD

**Issue by hadpro24** [stefanfoulis/django-phonenumber-field#545]
I test this phone but it passed test : `224623273737ff`

I test it with : validate_international_phonenumber

And I have this configuration:

```python
PHONENUMBER_DEFAULT_REGION = 'GN'
PHONENUMBER_DB_FORMAT = 'INTERNATIONAL'
PHONENUMBER_DEFAULT_FORMAT = 'INTERNATIONAL'
PHONENUMBER_UNKNOWN_REGION = 'GN'
```

**Comment by hadpro24** [comment]
I use django-phonenumber-field==6.4.0

**Comment by francoisfreitag** [comment]
Thanks for the report. It looks like a `libphonenumber` behavior:
https://github.com/google/libphonenumber/blob/f63cf2c9373d9c8f2b93ff87ee187560810c0686/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java#L3076-L3108

The `parse` utility ignores characters if it helps identifying a phone number. Depending on the sort of validation you’re expecting, it might make sense to implement your own validators on top of `phonenumber_field` to be more strict.
