### ISSUE TITLE
Italian translations incomplete

### ISSUE THREAD

**Issue by RuggeroFabbiano** [stefanfoulis/django-phonenumber-field#569]
Hello

There are a couple of translations missing in the Italian locale, that make the form error message appear in the default language when a wrong telephone number is submitted.

Happy to contribute if needed.

**Comment by francoisfreitag** [comment]
Yes please! You should be able to edit https://github.com/stefanfoulis/django-phonenumber-field/blob/main/phonenumber_field/locale/it/LC_MESSAGES/django.po on GitHub. The `msgid` is the original version of the string, and `msgstr` is the corresponding translation.

If you’re not confortable generating the `.mo` file, no worries, I’ll do it on the PR (be sure to [allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)).

Thanks in advance :star:

**Comment by francoisfreitag** [comment]
(note that strings marked as `fuzzy` could use an update as well)

**Comment by RuggeroFabbiano** [comment]
Sorry for the late reply, have been quite busy 😅
No worries, I'm quite used to how it works. I should be able to do it soon!

**Comment by RuggeroFabbiano** [comment]
I generated the `.mo` file, but I wasn't able to commit it due to them be Git-ignored.

**Comment by francoisfreitag** [comment]
Yes, I changed the release process to generate the MO file, so that git only follows the `.po` from now on. I didn’t think to come back to this PR.

Corresponding PR: https://github.com/stefanfoulis/django-phonenumber-field/pull/590
