### ISSUE TITLE
Create a new 0.7 version?

### ISSUE THREAD

**Issue by devangmundhra** [stefanfoulis/django-phonenumber-field#57]
The 0.6 version has some bugs (like`'NoneType' object has no attribute 'as_e164'`) which are resolved in merges there after, but difficult to get the latest version from pip.

**Comment by cyberjoac** [comment]
+1

**Comment by darylyu** [comment]
+1 I just ran into the probblem @devangmundhra brought up.

**Comment by basilkohler** [comment]
+1

**Comment by devfom** [comment]
+1

**Comment by jschneier** [comment]
+1

**Comment by danmoz** [comment]
+1

**Comment by khamaileon** [comment]
+1

**Comment by omerzimp** [comment]
@stefanfoulis I'm willing to take over the project and make a release just let me know when you added me as a collaborator.

**Comment by thedrow** [comment]
@stefanfoulis I'm willing to take over the project and make a release just let me know when you added me as a collaborator.

**Comment by darylyu** [comment]
For those looking for a quick temporary workaround, you can add this to your requirements.txt:

```
-e git+https://github.com/stefanfoulis/django-phonenumber-field@4dfdad11f#egg=django-phonenumber-field
```

**Comment by thedrow** [comment]
@darylyu Do you think it's time to fork?
I'd be happy to collaborate if @stefanfoulis is unresponsive.

**Comment by stefanfoulis** [comment]
oh, sorry. damn google mail filters. I'll make a release

**Comment by stefanfoulis** [comment]
0.7.1 released

**Comment by thedrow** [comment]
@stefanfoulis The offer still stands. I'd like to help with this project.
We're using it at work a lot.

**Comment by stefanfoulis** [comment]
@thedrow thank you very much for helping out :-) I added you as a collaborator.

**Comment by thedrow** [comment]
Wonderful.
I'll take a look at what needs to be done later on.
