### ISSUE TITLE
Multiple countrycodes in `PhoneNumberField`

### ISSUE THREAD

**Issue by kmartynski** [stefanfoulis/django-phonenumber-field#573]
Hi, I've been playing around with the library. I couldn't find any information around the web or in documentation.
Supposedly I have a model in Django

### settings.py
```
PHONENUMBER_DEFAULT_REGION = "PL"
PHONENUMBER_DEFAULT_FORMAT = "INTERNATIONAL"
```

### models.py
```
class Client(models.Model):
        phone = PhoneNumberField()
```

I'm not entirely sure if one might use many country codes, something like this:
```
class Client(models.Model):
        phone = PhoneNumberField(country_codes=["PL", "DE", "ES"])
```
Is there any option to accept phone numbers from many countries?

**Comment by kmartynski** [comment]
@francoisfreitag thank you for rapid response. 
So if I understand correctly by the second recommendation I should only stick to:
`PHONENUMBER_DEFAULT_FORMAT = "INTERNATIONAL"`

```
class Client(models.Model):
        phone = PhoneNumberField(region=None)
```
And remove 
`PHONENUMBER_DEFAULT_REGION = "PL"`

Is that right? :)

**Comment by francoisfreitag** [comment]
Yes, if you don’t want to interpret national phone numbers in your region, leaving `PHONENUMBER_DEFAULT_REGION` unspecified is the way to go. The system will then only accept phone numbers in an international format. To facilitate data entry for humans, you can use (or take inspiration from) the [PhoneNumberPrefixWidget](https://django-phonenumber-field.readthedocs.io/en/stable/reference.html#phonenumberprefixwidget).

As for the format, `INTERNATIONAL` is a good choice, it allows for international phone numbers, including phone extensions. https://django-phonenumber-field.readthedocs.io/en/stable/reference.html#phonenumber-db-format
