### ISSUE TITLE
Validation error with wrong locale

### ISSUE THREAD

**Issue by geclick** [stefanfoulis/django-phonenumber-field#575]
I have configured my Django project for using es-ES language and all messages and errors I get are in right locale, except the validation error message when the number is not valid. I'm getting "The phone number entered is not valid." when it should be "El número de teléfono ingresado no es válido." I also changed my project language to es-AR and still the same English error.

Django 4.1.3
django-phonenumber-field[phonenumberslite]==7.1.0

**Comment by francoisfreitag** [comment]
Did you forget to add `phonenumber_field` to your `INSTALLED_APPS` ?
https://django-phonenumber-field.readthedocs.io/en/latest/#setup
