### ISSUE TITLE
bug in python 3.10 

### ISSUE THREAD

**Issue by vanovarderesyan** [stefanfoulis/django-phonenumber-field#580]
ImportError: cannot import name 'MutableMapping' from 'collections'  

![image](https://github.com/stefanfoulis/django-phonenumber-field/assets/36670993/c96bbd2e-4678-40e2-ba69-223f9fa87e5f)

**Comment by francoisfreitag** [comment]
Looks like your babel version is likely too old. Not a bug in this package.

Can update babel with `env/bin/pip install --upgrade babel`.
