### ISSUE TITLE
Turkmenistan phone numbers has been updated

### ISSUE THREAD

**Issue by rowsen2904** [stefanfoulis/django-phonenumber-field#598]
Hi. Turkmen numbers used to be from 993-61, 993-65. But now they have introduced new numbers that are not in this package. for example, right now there are already numbers 993-71, etc. Looking forward to an update on this

**Comment by francoisfreitag** [comment]
The phone numbers schemes are handled by https://github.com/google/libphonenumber. Maybe upgrade your version of phonenumbers, or follow the update upstream.
