### ISSUE TITLE
The valid phonenumber is not accepted by this package

### ISSUE THREAD

**Issue by SathishNaqel** [stefanfoulis/django-phonenumber-field#599]
Hi Team,
We are using django-phonenumber-field ==5.2.0 and the valid phone number =966575566901.The valid phonenumber is not accepted by this package. Could you please let us know how to include this in the validation to accept. 

Thanks,
Sathish

**Comment by francoisfreitag** [comment]
Hi Sathish,

The phone numbers are validated by https://github.com/google/libphonenumber. If you believe there’s a valid phone number that has been wrongly flagged as invalid, please report the issue there with the exact phone numbers and why you believe it is valid.

**Comment by laksithakumara-cb** [comment]
@francoisfreitag This is a valid issue. Please update the phonenumbers module; otherwise, some phone numbers are incorrectly marked as invalid.

**Comment by francoisfreitag** [comment]
The `phonenumbers` library is unconstrained, so you can use the latest version available in your environment.
https://github.com/stefanfoulis/django-phonenumber-field/blob/89b06b32d8c2955099b3f591ab2b6bb7aa4f362c/pyproject.toml#L39-L41
