### ISSUE TITLE
object has no attribute 'model'

### ISSUE THREAD

**Issue by kalvish21** [stefanfoulis/django-phonenumber-field#60]
I'm declaring it like this in my form class:

    phone = PhoneNumberField(blank=True)

In my template I use this:

    {{form.phone}}

And I get the error in my debug mode:

    'PhoneNumberField' object has no attribute 'model'

Is there anything i'm doing wrong here?

**Comment by amateja** [comment]
I'm afraid you shared a bit too little information. Can you elaborate to help us recreate your problem?

**Comment by amateja** [comment]
Thank you for reporting. Our project has evolved since that time and this issue will be closed. Please update and reopen if you feel it is still applicable.
