### ISSUE TITLE
0493 prefix invalid numbet Australia

### ISSUE THREAD

**Issue by Sainadhilla** [stefanfoulis/django-phonenumber-field#600]
Can someone help me to validate my phone number starts with 0493.is is showing invalid number in some apps and websites

**Comment by francoisfreitag** [comment]
The phone numbers are validated by https://github.com/google/libphonenumber. If you believe there’s a valid phone number that has been wrongly flagged as invalid, please report the issue there with the exact phone numbers and why you believe it is valid.
