### ISSUE TITLE
Add note on 'PHONENUMBER_DEFAULT_REGION'

### ISSUE THREAD

**Issue by halfnibble** [stefanfoulis/django-phonenumber-field#66]
If there is a separate documentation website, then it'd be cool to show a link to it in the Readme.

If not, it'd be nice to document the 'PHONENUMBER_DEFAULT_REGION' feature. If you want me to, I can send a pull request with a modified Readme. 

Thanks.

**Comment by codexterous** [comment]
I absolutely agree. Spent a half hour looking for this information - shouldn't have to look in the source for it.

**Comment by LennyLip** [comment]
+1

**Comment by LennyLip** [comment]
+ PHONENUMBER_DEFAULT_FORMAT

**Comment by Power-Inside** [comment]
:+1: Anything on this yet?

**Comment by Lauriy** [comment]
+1

**Comment by xpostudio4** [comment]
Anything on this yet?, anyone can provide the reference link here, I promise I will add it immediately.

**Comment by amateja** [comment]
Thank you for reporting. Our project has evolved since that time and this issue will be closed. Please update and reopen if you feel it is still applicable.

**Comment by ritiko** [comment]
It looks like PHONENUMBER_DEFAULT_FORMAT was never actually added to the README. Can we re-open this issue? It's still used in code: https://github.com/stefanfoulis/django-phonenumber-field/blob/76c78b3c04984c48fc2d07d5be939bd548754788/phonenumber_field/phonenumber.py#L34
