### ISSUE TITLE
Add Support for Django Rest Framework

### ISSUE THREAD

**Issue by cancan101** [stefanfoulis/django-phonenumber-field#72]
[django-rest-framework-gis](https://github.com/djangonauts/django-rest-framework-gis) might be a good example.

**Comment by bartmika** [comment]
+1

**Comment by max-pfeiffer** [comment]
+1

**Comment by icam0** [comment]
+1

**Comment by ACPrice** [comment]
+1

**Comment by stefanfoulis** [comment]
Do you mean django-rest-framework serialiser support for the field?

**Comment by ACPrice** [comment]
Not sure what @cancan101 had in mind, but yeah, after integrating PhoneNumberField into a DRF project yesterday, I think I do mean that I'd like DRF to support the field.

**Comment by cancan101** [comment]
Right now I am doing something like this for Serializing a phone number: 

```python
    phone_number = serializers.CharField(
        validators=PhoneNumberField().validators, ...)
```

**Comment by ACPrice** [comment]
@cancan101 Super helpful! I was trying to figure out how to validate in the serializer yesterday.

**Comment by amateja** [comment]
Thank you for reporting. Our project has evolved since that time and this issue will be closed. Please update and reopen if you feel it is still applicable.
