### ISSUE TITLE
PhoneNumberField with max_length of 128.

### ISSUE THREAD

**Issue by chronossc** [stefanfoulis/django-phonenumber-field#89]
Hello Stefan :).

I was checking my migration and found that `PhoneNumberField` has `max_legth` of 128. I have found a bit weird this giant phone number size and since you are enforcing it and I had no tip checking commits I'm here asking why 128 instead something like 20 (1 for +, 3 for country code, 3 for area code, 13 for phone digits).

The code is at https://github.com/stefanfoulis/django-phonenumber-field/blame/develop/phonenumber_field/modelfields.py#L48

```python
class PhoneNumberField(models.Field):
    attr_class = PhoneNumber
    descriptor_class = PhoneNumberDescriptor
    default_validators = [validate_international_phonenumber]

    description = _("Phone number")

    def __init__(self, *args, **kwargs):
        kwargs['max_length'] = kwargs.get('max_length', 128)
        super(PhoneNumberField, self).__init__(*args, **kwargs)
        self.validators.append(validators.MaxLengthValidator(self.max_length))
``` 

Thx man.

**Comment by stefanfoulis** [comment]
The value is just so hight to definitely be large enough for all phone numbers. And didn't see a performance impact in just setting it at this size. I guess something like 32 would have been enough as well.
Annoyingly this is not easy to change in hindsight. If we just change the value here, people using this field in re-usable apps will produce different database migrations based on which version of django-phonenumber-field they happen to have had installed when they created their migration. So it is likely that people will get warnings about missing migrations in a re-usable app (which they don't have control over), if they upgrade django-phonenumber-field in their project.

IMHO there is no significant performance reason to go through that hassle for this change. But I'm no database expert, so I may be wrong :-)

**Comment by chronossc** [comment]
You are right, it don't have penalty on performance because `CharField`  use `varchar` in MySQL and PostgreSQL at least and so use only necessary bytes, I agree that isn't needed to change the field size, but a comment on code or docs about the size would be nice (maybe that issue will work as documentation too). Anyway I was more curious about why use that size :D.

Thx for reply and btw, good job u have done in this fields :+1: .

**Comment by kevin-brown** [comment]
> instead something like 20 (1 for +, 3 for country code, 3 for area code, 13 for phone digits).

You're missing extensions to phone numbers in there (`;ext=123`) and also that some people use formats other than E164 for the database.
