### ISSUE TITLE
unhashable type: 'PhoneNumber'

### ISSUE THREAD

**Issue by georgekpg** [stefanfoulis/django-phonenumber-field#93]
When I used PhoneNumberField(unique=True) I have got the error
"unhashable type: 'PhoneNumber'" because phonenumber_field.phonenumber.PhoneNumber doesn't implement \_\_hash\_\_ method.

I used workaround

    def PhoneNumberHash(self):
        return hash(self.as_e164)
    
    PhoneNumber.__hash__ = PhoneNumberHash

and it fixes the problem, but it would be better to place this in the app's code

**Comment by amateja** [comment]
I could be wrong... but PhoneNumberField class does not need to implement __hash__ method as long as its parend does that and there is a __hash__ method in django.db.models.Field class. Moreover I successfully created a field with unique=True attribute. Could you recheck it?

**Comment by georgekpg** [comment]
Hi, Andrzej!

I just have removed my workaround and problem is still here.
It raises not at model creation time but when I am filling data in django admin.

TypeError at /admin/tickets/person/953/change/
unhashable type: 'PhoneNumber'
Request Method:	POST
Request URL:	http://127.0.0.1:8000/admin/tickets/person/953/change/
Django Version:	1.9.2
Exception Type:	TypeError
Exception Value:	
unhashable type: 'PhoneNumber'
Exception Location:	/home/george/sd.venv/lib/python3.5/site-packages/django/forms/models.py in validate_unique, line 677
Python Executable:	/home/george/sd.venv/bin/python
Python Version:	3.5.1
Python Path:	
['/home/george/sd.project',
  '/usr/local/lib/python35.zip',
  '/usr/local/lib/python3.5',
  '/usr/local/lib/python3.5/plat-linux',
  '/usr/local/lib/python3.5/lib-dynload',
  '/home/george/sd.venv/lib/python3.5/site-packages']
Server time:	Пн, 29 Фев 2016 14:38:30 +0300


My virtual environment is (pip freeze --local)
Babel==2.2.0
Django==1.9.2
django-admin-tools==0.7.2
django-bootstrap3==6.2.2
django-datetime-widget==0.9.3
django-enumfield==1.3b2
django-mptt==0.8.0
django-phonenumber-field==1.0.0
django-simple-history==1.7.0
feedparser==5.2.1
handy==0.5.4
phonenumbers==7.2.6
Pillow==3.1.0
psycopg2==2.6.1
pyodbc==3.0.10
pytz==2015.7
PyYAML==3.11
six==1.10.0
uWSGI==2.0.12


Maybe I am wrong and problem is not in PhoneNumberField class but in PhoneNumber class.

29.02.2016 16:30, Andrzej Mateja пишет:

**Comment by amateja** [comment]
Hi,

Thank you for this clarification. From what you write I learn that the best place for your request is [python-phonenumbers](https://github.com/daviddrysdale/python-phonenumbers/) project. PhoneNumber class basically comes from that project and patching it here is not the clearest way I think.

**Comment by wojtek-fliposports** [comment]
related to bug https://code.djangoproject.com/ticket/26819

**Comment by tredzko** [comment]
Have you tried upgrading your django-phonenumber-field? The current version is [1.3.0](https://pypi.python.org/pypi/django-phonenumber-field/1.3.0), yours appears to be pinned to 1.0.0. 1.3.0 has the changes from #151 added to it.

**Comment by georgekpg** [comment]
Hi @tredzko. You are right, I have found that this problem is fixed in the recent versions.
