### ISSUE TITLE
'dict' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by kabaka0** [stefanfoulis/django-phonenumber-field#95]
Installed version 0.7.2 in a Python 3.5 environment.  On running, received error

Django Version: 	1.8.4
Exception Type: 	AttributeError
Exception Value: 	

'dict' object has no attribute 'iteritems'

Exception Location: 	.../lib/python3.5/site-packages/phonenumber_field/widgets.py in __init__, line 21

Solution was to replace 
...
or prefix, values in _COUNTRY_CODE_TO_REGION_CODE.iteritems():
...

with 
...
or prefix, values in _COUNTRY_CODE_TO_REGION_CODE.items():
...

**Comment by Godod** [comment]
Hello. I have the same bug. Please fix bug.
