### ISSUE TITLE
Enter Valid Phone Number Form Error

### ISSUE THREAD

**Issue by stcalica** [stefanfoulis/django-phonenumber-field#99]
I keep getting this form error even though I have formatted my number in the following ways: 

+1 01 212 555-2345
+1 01 212 5552345
+15552345
15552345
5552345
212 555 2345
2125552345

This is my model:

class Contact(models.Model):
	phone = PhoneNumberField(blank=True) 

This is my Form: 

class ExpForm(forms.Form):
	phone = PhoneNumberField()

And this is my template for phone: 

                               <div  id="phone" class="form_field">
				{{ form.phone.errors }}
				<label>{{ form.phone.label_tag }}</label>
				{{ form.phone }}
				</div>

How are the numbers supposed to be formatted for the Form fields? 
I couldn't find any examples.

**Comment by haywhisksoftware** [comment]
Are you using the `PhoneNumberPrefixWidget` for your phone field?

I was able to enter phone numbers once I started using that widget.

**Comment by amateja** [comment]
Thank you for reporting. Our project has evolved since that time and this issue will be closed. Please update and reopen if you feel it is still applicable.

**Comment by tochimclaren** [comment]
I am still getting the invalid phone validation error

**Comment by Benjamin-Kozuch** [comment]
try +19998887777 (american)

where 999 is the area code and 8887777 is the actual number

**Comment by fromRussiaImportLove** [comment]
I have invalid phone validation error, when i try use +7 code country. If i start number from +1 it's ok. But i need multicultural form. Can you, please, give me any advice?

**Comment by Wemaka** [comment]
Как можно изменить текст ошибки "Enter a valid phone number (e.g. +12125552368)." ?

**Comment by Wemaka** [comment]
> How can I change the error text "Enter a valid phone number (e.g. +12125552368)." ?

**Comment by francoisfreitag** [comment]
This issue has been closed, and it’s hard to pick what is expected and what happens.
If you think there’s an issue, please open a GitHub issue explaining:
- What you are doing (code excerpts are welcome)
- What happens
- What you expected

Thanks!
